package com.sofe.client;

import java.util.Map;

/**
 * The class of each class unique, for tooltips (the Relic data lives on the server). Written by
 * scripts/make_uniques.py from scripts/uniques_catalog.py.
 */
public final class UniqueClasses {
    private static final Map<String, String> CLASSES = Map.ofEntries(
            Map.entry("sunder_of_the_order", "knight"),
            Map.entry("verdict_of_cassian", "knight"),
            Map.entry("broken_banner_lance", "knight"),
            Map.entry("anvil_of_aureum", "knight"),
            Map.entry("oathkeeper", "knight"),
            Map.entry("wrath_unbound", "knight"),
            Map.entry("helm_of_the_last_knight", "knight"),
            Map.entry("crown_of_the_scale", "knight"),
            Map.entry("bulwark_cuirass", "knight"),
            Map.entry("heart_of_the_legion", "knight"),
            Map.entry("greaves_of_the_vigil", "knight"),
            Map.entry("legs_of_the_unyielding", "knight"),
            Map.entry("march_of_the_paladin", "knight"),
            Map.entry("iron_roots", "knight"),
            Map.entry("signet_of_the_order", "knight"),
            Map.entry("band_of_unbroken_oaths", "knight"),
            Map.entry("medal_of_the_scale", "knight"),
            Map.entry("tear_of_aureum", "knight"),
            Map.entry("knight_shield_charm", "knight"),
            Map.entry("knight_banner_charm", "knight"),
            Map.entry("knight_wrath_charm", "knight"),
            Map.entry("knight_grand_charm", "knight"),
            Map.entry("wand_of_the_ferryman", "necromancer"),
            Map.entry("thoth_reed", "necromancer"),
            Map.entry("staff_of_the_nine_gates", "necromancer"),
            Map.entry("sickle_of_morthis", "necromancer"),
            Map.entry("khopesh_of_the_embalmer", "necromancer"),
            Map.entry("anubets_judgement", "necromancer"),
            Map.entry("mask_of_the_ferryman", "necromancer"),
            Map.entry("crown_of_the_pale_king", "necromancer"),
            Map.entry("shroud_of_khemet", "necromancer"),
            Map.entry("ribcage_of_the_lich", "necromancer"),
            Map.entry("wraps_of_the_long_sleep", "necromancer"),
            Map.entry("grave_dust_trousers", "necromancer"),
            Map.entry("sandals_of_the_threshold", "necromancer"),
            Map.entry("treads_of_the_underworld", "necromancer"),
            Map.entry("ring_of_bound_souls", "necromancer"),
            Map.entry("seal_of_the_house_of_thresholds", "necromancer"),
            Map.entry("heart_scarab", "necromancer"),
            Map.entry("eye_of_morthis", "necromancer"),
            Map.entry("necro_scarab_charm", "necromancer"),
            Map.entry("necro_ankh_charm", "necromancer"),
            Map.entry("necro_jar_charm", "necromancer"),
            Map.entry("necro_grand_charm", "necromancer"),
            Map.entry("laleh_lantern", "sorceress"),
            Map.entry("tear_of_the_moon", "sorceress"),
            Map.entry("astrolabe_of_shirin", "sorceress"),
            Map.entry("pen_of_the_poet_king", "sorceress"),
            Map.entry("staff_of_winter_gardens", "sorceress"),
            Map.entry("skyfall", "sorceress"),
            Map.entry("veil_of_laleh", "sorceress"),
            Map.entry("hat_of_the_circle", "sorceress"),
            Map.entry("robe_of_written_stars", "sorceress"),
            Map.entry("mantle_of_the_eclipse", "sorceress"),
            Map.entry("silks_of_parsivan", "sorceress"),
            Map.entry("leggings_of_the_storm_court", "sorceress"),
            Map.entry("slippers_of_the_waterline", "sorceress"),
            Map.entry("steps_of_the_comet", "sorceress"),
            Map.entry("ring_of_three_runes", "sorceress"),
            Map.entry("band_of_the_constellation", "sorceress"),
            Map.entry("star_of_parsivan", "sorceress"),
            Map.entry("lalehs_locket", "sorceress"),
            Map.entry("sorc_ember_charm", "sorceress"),
            Map.entry("sorc_frost_charm", "sorceress"),
            Map.entry("sorc_storm_charm", "sorceress"),
            Map.entry("sorc_grand_charm", "sorceress"),
            Map.entry("ash_and_ember", "thief"),
            Map.entry("fangs_of_fenrath", "thief"),
            Map.entry("smugglers_seax", "thief"),
            Map.entry("last_breath", "thief"),
            Map.entry("fjord_wolf_hook", "thief"),
            Map.entry("greed_incarnate", "thief"),
            Map.entry("hood_of_ash", "thief"),
            Map.entry("mask_of_the_heist", "thief"),
            Map.entry("jerkin_of_many_pockets", "thief"),
            Map.entry("wolfskin_of_the_raider", "thief"),
            Map.entry("breeches_of_the_cutpurse", "thief"),
            Map.entry("shadowstep_legwraps", "thief"),
            Map.entry("boots_of_the_fjord_runner", "thief"),
            Map.entry("silent_soles", "thief"),
            Map.entry("ring_of_the_fence", "thief"),
            Map.entry("knot_of_the_grimsson_clan", "thief"),
            Map.entry("wolf_tooth_necklace", "thief"),
            Map.entry("ember_of_the_burned_village", "thief"),
            Map.entry("thief_coin_charm", "thief"),
            Map.entry("thief_key_charm", "thief"),
            Map.entry("thief_fang_charm", "thief"),
            Map.entry("thief_grand_charm", "thief"),
            Map.entry("scepter_of_the_first_sultan", "king"),
            Map.entry("azhar_crescent", "king"),
            Map.entry("voice_of_the_cannon", "king"),
            Map.entry("janissary_oath", "king"),
            Map.entry("musket_of_the_siege", "king"),
            Map.entry("halberd_of_five_lands", "king"),
            Map.entry("turban_of_the_peacock_throne", "king"),
            Map.entry("crown_of_azhar", "king"),
            Map.entry("kaftan_of_the_divan", "king"),
            Map.entry("robes_of_the_golden_age", "king"),
            Map.entry("trousers_of_the_vizier", "king"),
            Map.entry("legs_of_the_conqueror", "king"),
            Map.entry("slippers_of_the_harem_road", "king"),
            Map.entry("tread_of_kings", "king"),
            Map.entry("signet_of_tevfiran", "king"),
            Map.entry("ring_of_the_grand_vizier", "king"),
            Map.entry("crescent_of_sulthari", "king"),
            Map.entry("heart_of_the_throne", "king"),
            Map.entry("king_coin_charm", "king"),
            Map.entry("king_decree_charm", "king"),
            Map.entry("king_cannon_charm", "king"),
            Map.entry("king_grand_charm", "king"));

    private UniqueClasses() {
    }

    /** The class id that may use this unique, or null for anyone. */
    public static String of(String relic) {
        return CLASSES.get(relic);
    }
}
