"""Every SoFE armor set, ten per class, and the unique armor pieces: what each looks like (its parts and
palette), who it is for, its level and weight, its names and its full-set bonus. scripts/make_armor_models.py
builds the models and icons from here; scripts/make_armor_data.py the items, lang, gear bases and bonuses.

weight: "heavy" plate asks for Strength like Diablo's (12 + 1.5 x level), "medium" asks for less (10 + 0.75 x level),
"light" robes and leathers ask for nothing. style: the piece names (plate, robe, leather, royal).
"""
from armor_lib import *  # noqa: F401,F403 (the parts)


def heavy(head, plate="plate", trim="trim", big=1.2, mark=None, extra=(), cape_mat=None, legs_extra=()):
    parts = list(head) + [body_plate(plate), breastplate(plate, mark), gorget(trim), belt(trim, "gem"), tassets(plate),
                          arm_plate(plate), pauldron(plate, trim, 3, big), vambrace(plate, trim),
                          leg_plate(plate), knee(trim), thigh_guard(plate), boots(plate, trim)] + list(legs_extra) + list(extra)
    if cape_mat:
        parts.append(cape(cape_mat))
    return parts


def robe(head, cloth="cloth", trim="trim", mark=None, extra=(), full=True, shoes=True):
    parts = list(head) + [body_plate(cloth, 1.0), belt(trim, "gem"), arm_plate(cloth, 0.5), wide_sleeve(cloth, trim),
                          leg_plate(cloth, 0.4)]
    parts.append(robe_full(cloth, trim) if full else robe_skirt(cloth))
    parts.append(curled_shoes(cloth, trim) if shoes else wraps(cloth))
    if mark:
        parts.append(emblem(mark, trim))
    return parts + list(extra)


def leather(head, mat="leather", trim="trim", extra=(), fur=None, coat=False):
    parts = list(head) + [body_plate(mat, 1.0), straps(mat), belt(trim, "gem"), arm_plate(mat, 0.6), vambrace(mat, trim),
                          leg_plate(mat, 0.5), knee(mat)]
    parts.append(fur_boots(mat, fur) if fur else boots(mat, trim, toe=False))
    if coat:
        parts.append(coat_tails(mat))
    return parts + list(extra)


def royal(head, silk="cloth", trim="trim", extra=(), mark=None, skirt=True):
    parts = list(head) + [body_plate(silk, 1.0), sash("cloth2"), gorget(trim), arm_plate(silk, 0.55), sleeve(silk),
                          leg_plate(silk, 0.45), curled_shoes(silk, trim)]
    parts.append(robe_skirt(silk) if skirt else coat_tails(silk))
    if mark:
        parts.append(emblem(mark, trim))
    return parts + list(extra)


def eff(effect, amp=0, when="always"):
    return {"type": "effect", "effect": "minecraft:" + effect, "amplifier": amp, "when": when}


def answer(action, value=0):
    return {"type": "answer", "action": action, "value": value}


def on_kill(**kw):
    return dict({"type": "on_kill"}, **kw)


# name: class, level, weight, style, (en, es), head names (en, es) or None, palette, parts, bonuses, (bonus en, bonus es), repair
SETS = [
    # ------------------------------------------------------------------- the knight: Aureum plate
    dict(name="bronze", cls="knight", level=6, weight="heavy", style="plate", names=("Bronze", "de Bronce"),
         pal={"plate": (176, 106, 50), "trim": (222, 170, 90), "cloth2": (170, 30, 30), "gem": (60, 200, 190)},
         parts=heavy([helmet_shell("plate"), cheek_guards("plate"), plume("cloth2")], mark="sun", big=1.0),
         bonus=[{"type": "absorption", "every": 600}], text=("Full set: a shield of absorption every 30 seconds",
                                                              "Set completo: un escudo de absorción cada 30 segundos")),
    dict(name="legion", cls="knight", level=74, weight="heavy", style="plate", names=("Legion", "de la Legión"),
         pal={"plate": (52, 82, 170), "trim": (232, 186, 70), "cloth2": (190, 30, 30), "cloth": (170, 28, 28), "gem": (255, 220, 120)},
         parts=heavy([helmet_shell("plate"), cheek_guards("trim"), plume("cloth2"), brow("trim")], mark="laurel", cape_mat="cloth"),
         bonus=[answer("knockback", 0.8)], text=("Full set: knock back whoever strikes you", "Set completo: empujas a quien te golpea")),
    dict(name="cobalt", cls="knight", level=36, weight="heavy", style="plate", names=("Cobalt", "de Cobalto"),
         pal={"plate": (40, 78, 176), "trim": (210, 214, 226), "gem": (240, 250, 255)},
         parts=heavy([great_helm("plate", "trim"), wings("trim")], mark="star", big=1.4),
         bonus=[eff("resistance")], text=("Full set: take less damage", "Set completo: recibes menos daño")),
    dict(name="scale", cls="knight", level=84, weight="heavy", style="plate", names=("Order of the Scale", "de la Orden de la Balanza"),
         pal={"plate": (216, 220, 230), "trim": (232, 186, 70), "cloth": (40, 70, 170), "gem": (90, 140, 255)},
         parts=heavy([great_helm("plate", "trim"), halo("trim")], mark="scale", cape_mat="cloth", extra=[surcoat("cloth", "scale")]),
         bonus=[answer("reflect", 0.25)], text=("Full set: a quarter of melee damage returns to the attacker",
                                                "Set completo: un cuarto del daño cuerpo a cuerpo vuelve al atacante")),
    dict(name="solari", cls="knight", level=50, weight="heavy", style="plate", names=("Solari", "Solari"),
         pal={"plate": (196, 44, 34), "trim": (238, 178, 52), "gem": (255, 90, 40), "cloth": (150, 24, 24)},
         parts=heavy([helmet_shell("plate"), brow("trim"), sun_crown("trim", "gem"), crest("trim"), cheek_guards("trim")], mark="sun"),
         bonus=[eff("fire_resistance")], text=("Full set: immune to fire", "Set completo: inmune al fuego")),
    dict(name="glacial_iron", cls="knight", level=24, weight="heavy", style="plate", names=("Glacial Iron", "de Hierro Glacial"),
         pal={"plate": (130, 190, 230), "trim": (240, 250, 255), "gem": (120, 230, 255), "fur": (230, 236, 240)},
         parts=heavy([helmet_shell("plate"), nasal("plate"), crest("trim")], mark="snowflake", extra=[crystals("gem"), fur_mantle("fur")]),
         bonus=[answer("slow"), {"type": "unfreeze"}], text=("Full set: the cold never takes you, and whoever strikes you is slowed",
                                                            "Set completo: el frío nunca te alcanza, y quien te golpea queda ralentizado")),
    dict(name="sentinel", cls="knight", level=16, weight="heavy", style="plate", names=("Sentinel", "del Centinela"),
         pal={"plate": (150, 156, 168), "trim": (120, 80, 40), "cloth": (200, 196, 180), "gem": (190, 30, 30)},
         parts=heavy([great_helm("plate", "trim")], mark=None, big=1.1, extra=[surcoat("cloth", "rune")]),
         bonus=[eff("resistance", 1, "low_health")], text=("Full set: Resistance II while below half health",
                                                           "Set completo: Resistencia II con menos de media vida")),
    dict(name="dragonknight", cls="knight", level=60, weight="heavy", style="plate", names=("Dragonknight", "del Caballero Dragón"),
         pal={"plate": (40, 110, 60), "trim": (210, 170, 70), "bone": (230, 220, 190), "gem": (255, 110, 40), "cloth": (120, 20, 20)},
         parts=heavy([dragon_helm("plate", "bone", "gem")], mark="dragon", big=1.3, extra=[spiked_pauldron("plate", "bone")], cape_mat="cloth"),
         bonus=[eff("regeneration", 0, "low_health"), eff("fire_resistance")],
         text=("Full set: immune to fire, and you regenerate while below half health",
               "Set completo: inmune al fuego, y te regeneras con menos de media vida")),
    dict(name="warlord", cls="knight", level=40, weight="heavy", style="plate", names=("Warlord", "del Señor de la Guerra"),
         pal={"plate": (52, 50, 56), "trim": (170, 40, 30), "bone": (220, 210, 190), "gem": (255, 60, 40)},
         parts=heavy([great_helm("plate", "trim"), demon_horns("bone")], mark="skull_emblem", big=1.5, extra=[spiked_pauldron("plate", "bone", "trim")]),
         bonus=[eff("resistance"), eff("strength"), eff("slowness")],
         text=("Full set: Strength and Resistance, but the weight slows you", "Set completo: Fuerza y Resistencia, pero el peso te ralentiza")),
    dict(name="infernal", cls="knight", level=94, weight="heavy", style="plate", names=("Infernal", "Infernal"),
         pal={"plate": (70, 22, 14), "trim": (255, 130, 40), "bone": (40, 30, 30), "gem": (255, 200, 80)},
         parts=heavy([helmet_shell("plate"), demon_horns("bone"), brow("trim", "gem")], mark="flame", big=1.4, extra=[flames("gem"), spiked_pauldron("plate", "bone")]),
         bonus=[answer("ignite", 4)], text=("Full set: set fire to whoever strikes you", "Set completo: incendias a quien te golpea")),

    # ------------------------------------------------------------------- the necromancer: Khemet, bone and souls
    dict(name="embalmer", cls="necromancer", level=50, weight="light", style="robe", names=("Embalmer", "del Embalsamador"),
         head=("Jackal Headdress", "Tocado de Chacal"),
         pal={"plate": (226, 214, 186), "cloth": (236, 228, 206), "trim": (226, 176, 56), "dark": (30, 30, 40), "gem": (50, 210, 200)},
         parts=robe([nemes("cloth", "trim"), jackal_headdress("dark", "trim")], mark="eye_emblem", extra=[pauldron("trim", "gem", 2, 0.9)]),
         bonus=[eff("regeneration", 0, "crouching")], text=("Full set: regenerate while crouching", "Set completo: te regeneras agachado")),
    dict(name="scarab", cls="necromancer", level=50, weight="medium", style="plate", names=("Scarab", "del Escarabajo"),
         head=("Scarab Crown", "Corona del Escarabajo"),
         pal={"plate": (214, 168, 48), "trim": (30, 150, 140), "cloth": (240, 232, 210), "gem": (50, 220, 200), "trim2": (40, 70, 160)},
         parts=heavy([nemes("plate", "trim"), uraeus("trim", "gem")], plate="plate", trim="trim", big=1.0, mark="ankh", extra=[robe_skirt("cloth")]),
         bonus=[{"type": "cleanse", "effects": ["minecraft:poison", "minecraft:wither"]}],
         text=("Full set: poison and wither do not take hold", "Set completo: el veneno y la descomposición no te afectan")),
    dict(name="void", cls="necromancer", level=74, weight="medium", style="robe", names=("Void-infused", "del Vacío"),
         head=("Void Cowl", "Capucha del Vacío"),
         pal={"cloth": (40, 18, 66), "plate": (30, 14, 50), "trim": (150, 80, 230), "gem": (220, 150, 255), "dark": (10, 4, 18)},
         parts=robe([hood_deep("cloth", "dark")], mark="eye_emblem", extra=[shoulder_orbs("gem", "trim"), high_collar("cloth", "trim")]),
         bonus=[eff("strength")], text=("Full set: strength of the Void", "Set completo: fuerza del Vacío")),
    dict(name="gravewarden", cls="necromancer", level=14, weight="light", style="robe", names=("Gravewarden", "del Guardatumbas"),
         head=("Gravewarden Hood", "Capucha del Guardatumbas"),
         pal={"cloth": (60, 64, 60), "trim": (150, 140, 110), "bone": (214, 204, 178), "gem": (110, 240, 220)},
         parts=robe([hood_deep("cloth", "bone")], mark="skull_emblem", extra=[bone_pauldron("bone")], shoes=False),
         bonus=[on_kill(heal=2.0)], text=("Full set: each kill heals you one heart", "Set completo: cada muerte te cura un corazón")),
    dict(name="bonelord", cls="necromancer", level=40, weight="medium", style="plate", names=("Bonelord", "del Señor de los Huesos"),
         head=("Skull of the Bonelord", "Cráneo del Señor de los Huesos"),
         pal={"plate": (90, 84, 76), "bone": (226, 214, 186), "trim": (120, 110, 90), "gem": (110, 240, 220), "cloth": (50, 44, 40)},
         parts=heavy([skull_helm("bone", "bone")], plate="plate", big=1.0, mark=None, extra=[ribcage("bone"), bone_pauldron("bone"), robe_skirt("cloth")]),
         bonus=[answer("wither")], text=("Full set: whoever strikes you withers", "Set completo: quien te golpea se marchita")),
    dict(name="anubis", cls="necromancer", level=84, weight="medium", style="robe", names=("Anubis", "de Anubis"),
         head=("Head of Anubis", "Cabeza de Anubis"),
         pal={"dark": (24, 24, 34), "cloth": (30, 32, 44), "trim": (232, 186, 70), "trim2": (40, 70, 170), "gem": (60, 230, 210), "plate": (36, 36, 50)},
         parts=robe([nemes("dark", "trim"), jackal_headdress("dark", "trim")], cloth="cloth", mark="ankh",
                    extra=[pauldron("trim", "trim2", 2, 1.0), gorget("trim")]),
         bonus=[{"type": "reveal", "radius": 16}, eff("night_vision")],
         text=("Full set: you see in the dark and enemies are revealed through walls",
               "Set completo: ves en la oscuridad y los enemigos se ven a través de las paredes")),
    dict(name="plaguebearer", cls="necromancer", level=30, weight="light", style="leather", names=("Plaguebearer", "del Portador de la Plaga"),
         head=("Plague Mask", "Máscara de la Plaga"),
         pal={"leather": (52, 40, 34), "dark": (24, 22, 24), "trim": (110, 120, 60), "gem": (150, 230, 80), "cloth": (40, 36, 34)},
         parts=leather([plague_mask("leather", "dark")], coat=True, extra=[high_collar("dark", "trim")]),
         bonus=[answer("poison")], text=("Full set: whoever strikes you is poisoned", "Set completo: quien te golpea queda envenenado")),
    dict(name="lich", cls="necromancer", level=94, weight="light", style="robe", names=("Lich", "del Liche"),
         head=("Lich Crown", "Corona del Liche"),
         pal={"cloth": (70, 30, 100), "trim": (200, 196, 180), "bone": (220, 214, 196), "gem": (110, 250, 230), "dark": (20, 10, 30)},
         parts=robe([hood_deep("cloth", "dark"), lich_crown("bone", "gem")], mark="skull_emblem",
                    extra=[bone_pauldron("bone"), shoulder_orbs("gem", "bone"), high_collar("cloth", "bone")]),
         bonus=[eff("invisibility", 0, "crouching"), on_kill(effect="minecraft:absorption", amplifier=0, duration=200)],
         text=("Full set: invisible while crouching, and each kill wraps you in a soul shield",
               "Set completo: invisible agachado, y cada muerte te envuelve en un escudo de almas")),
    dict(name="mummy_lord", cls="necromancer", level=60, weight="medium", style="robe", names=("Mummy Lord", "del Señor Momia"),
         head=("Funeral Mask", "Máscara Funeraria"),
         pal={"cloth": (206, 196, 168), "trim": (232, 186, 70), "gem": (40, 90, 200), "dark": (40, 30, 24)},
         parts=robe([mummy_wraps("cloth"), gold_mask("trim")], full=False, shoes=False, mark="ankh", extra=[gorget("trim"), pauldron("trim", "gem", 2, 0.9)]),
         bonus=[{"type": "cleanse", "effects": ["minecraft:hunger", "minecraft:weakness", "minecraft:slowness"]}, eff("regeneration", 0, "low_health")],
         text=("Full set: hunger, weakness and slowness do not take hold; you regenerate while below half health",
               "Set completo: el hambre, la debilidad y la lentitud no te afectan; te regeneras con menos de media vida")),
    dict(name="soulreaver", cls="necromancer", level=36, weight="medium", style="plate", names=("Soulreaver", "del Segador de Almas"),
         head=("Soulreaver Helm", "Yelmo del Segador de Almas"),
         pal={"plate": (40, 44, 54), "trim": (70, 200, 200), "gem": (120, 255, 240), "cloth": (24, 26, 34), "bone": (200, 200, 210)},
         parts=heavy([great_helm("plate", "trim"), lich_crown("plate", "gem")], big=1.2, mark="skull_emblem", cape_mat="cloth", extra=[flames("gem")]),
         bonus=[on_kill(effect="minecraft:speed", amplifier=1, duration=100), on_kill(heal=1.0)],
         text=("Full set: each kill quickens you and heals half a heart", "Set completo: cada muerte te acelera y cura medio corazón")),

    # ------------------------------------------------------------------- the sorceress: Parsivan robes and hats
    dict(name="chronomancer", cls="sorceress", level=50, weight="light", style="robe", names=("Chronomancer", "del Cronomante"),
         head=("Chronomancer Hat", "Sombrero del Cronomante"),
         pal={"cloth": (64, 42, 136), "trim": (226, 186, 80), "gem": (120, 230, 255)},
         parts=robe([wizard_hat("cloth", "trim", "gem")], mark="hourglass", extra=[high_collar("cloth", "trim")]),
         bonus=[eff("haste", 1)], text=("Full set: act faster (Haste II)", "Set completo: actúas más rápido (Prisa II)")),
    dict(name="observatory", cls="sorceress", level=30, weight="light", style="robe", names=("Observatory", "del Observatorio"),
         head=("Astronomer Hat", "Sombrero del Astrónomo"),
         pal={"cloth": (30, 50, 110), "trim": (206, 156, 66), "gem": (200, 230, 255), "plate": (160, 166, 184)},
         parts=robe([wizard_hat("cloth", "trim", "gem", brim=10)], mark="star", extra=[shoulder_orbs("trim", "gem")]),
         bonus=[eff("night_vision")], text=("Full set: see in the dark", "Set completo: ves en la oscuridad")),
    dict(name="emerald", cls="sorceress", level=36, weight="light", style="robe", names=("Emerald", "de Esmeralda"),
         head=("Emerald Circlet", "Diadema de Esmeralda"),
         pal={"cloth": (30, 120, 60), "trim": (220, 180, 80), "gem": (90, 240, 120), "cloth2": (240, 236, 214)},
         parts=robe([hood("cloth"), circlet("trim", "gem")], mark="laurel", extra=[crystals("gem"), sash("cloth2")]),
         bonus=[{"type": "heal", "every": 100, "amount": 1.0}], text=("Full set: heals half a heart every 5 seconds",
                                                                       "Set completo: cura medio corazón cada 5 segundos")),
    dict(name="archmage", cls="sorceress", level=84, weight="light", style="robe", names=("Archmage", "del Archimago"),
         head=("Archmage Hat", "Sombrero del Archimago"),
         pal={"cloth": (40, 60, 160), "trim": (240, 210, 110), "gem": (255, 240, 160), "cloth2": (230, 230, 245)},
         parts=robe([wizard_hat("cloth", "trim", "gem", brim=14)], mark="star", extra=[shoulder_orbs("gem", "trim"), high_collar("cloth", "trim"), cape("cloth")]),
         bonus=[eff("slow_falling", 0, "falling"), eff("regeneration", 0, "crouching")],
         text=("Full set: you float down when falling and regenerate while crouching",
               "Set completo: caes flotando y te regeneras agachado")),
    dict(name="pyromancer", cls="sorceress", level=40, weight="light", style="robe", names=("Pyromancer", "del Piromante"),
         head=("Pyromancer Hat", "Sombrero del Piromante"),
         pal={"cloth": (170, 40, 20), "trim": (255, 170, 50), "gem": (255, 220, 90), "dark": (40, 14, 10)},
         parts=robe([wizard_hat("cloth", "trim", "gem")], mark="flame", extra=[flames("gem"), sash("dark")]),
         bonus=[eff("fire_resistance"), answer("ignite", 3)], text=("Full set: immune to fire, and whoever strikes you burns",
                                                                    "Set completo: inmune al fuego, y quien te golpea arde")),
    dict(name="frost_witch", cls="sorceress", level=24, weight="light", style="robe", names=("Frost Witch", "de la Bruja de Escarcha"),
         head=("Ice Crown", "Corona de Hielo"),
         pal={"cloth": (150, 200, 236), "trim": (240, 250, 255), "gem": (170, 240, 255), "fur": (236, 240, 246)},
         parts=robe([hood("cloth"), lich_crown("gem", "trim")], mark="snowflake", extra=[crystals("gem"), fur_mantle("fur")]),
         bonus=[answer("slow"), {"type": "unfreeze"}], text=("Full set: the cold never takes you, and whoever strikes you is slowed",
                                                            "Set completo: el frío nunca te alcanza, y quien te golpea queda ralentizado")),
    dict(name="tempest", cls="sorceress", level=60, weight="light", style="robe", names=("Tempest", "de la Tempestad"),
         head=("Storm Hood", "Capucha de la Tormenta"),
         pal={"cloth": (70, 80, 100), "trim": (255, 230, 90), "gem": (190, 230, 255), "cloth2": (40, 46, 60)},
         parts=robe([hood_deep("cloth"), circlet("trim", "gem")], mark="rune", extra=[shoulder_orbs("gem", "trim"), cape("cloth2")]),
         bonus=[eff("speed", 1), eff("jump_boost", 1)], text=("Full set: swift as the storm: Speed II and Jump Boost II",
                                                                  "Set completo: veloz como la tormenta: Velocidad II y Salto II")),
    dict(name="enchantress", cls="sorceress", level=16, weight="light", style="robe", names=("Enchantress", "de la Encantadora"),
         head=("Veil of the Enchantress", "Velo de la Encantadora"),
         pal={"cloth": (40, 170, 170), "cloth2": (230, 200, 230), "trim": (236, 190, 80), "gem": (240, 80, 160)},
         parts=robe([hood("cloth"), circlet("trim", "gem"), veil("cloth2")], mark="peacock", extra=[sash("cloth2")]),
         bonus=[answer("weakness")], text=("Full set: whoever strikes you is weakened", "Set completo: quien te golpea queda debilitado")),
    dict(name="witch", cls="sorceress", level=6, weight="light", style="robe", names=("Witch", "de la Bruja"),
         head=("Witch Hat", "Sombrero de Bruja"),
         pal={"cloth": (36, 30, 44), "trim": (110, 170, 60), "gem": (170, 240, 90), "cloth2": (80, 30, 90)},
         parts=robe([witch_hat("cloth", "trim", "gem")], mark="crescent", extra=[sash("cloth2")]),
         bonus=[{"type": "cleanse", "effects": ["minecraft:poison"]}, eff("luck")],
         text=("Full set: poison does not take hold, and luck is with you", "Set completo: el veneno no te afecta, y la suerte te acompaña")),
    dict(name="astral_sage", cls="sorceress", level=94, weight="light", style="robe", names=("Astral Sage", "del Sabio Astral"),
         head=("Astral Halo", "Halo Astral"),
         pal={"cloth": (236, 232, 220), "trim": (240, 200, 90), "gem": (150, 200, 255), "cloth2": (60, 70, 150)},
         parts=robe([hood("cloth"), halo("trim"), circlet("trim", "gem")], mark="sun", extra=[shoulder_orbs("gem", "trim"), high_collar("cloth", "trim"), cape("cloth2")]),
         bonus=[{"type": "absorption", "every": 400}, eff("night_vision")],
         text=("Full set: you see in the dark and a shield of starlight returns every 20 seconds",
               "Set completo: ves en la oscuridad y un escudo de luz estelar vuelve cada 20 segundos")),

    # ------------------------------------------------------------------- the thief: Nordrath leather, hoods and furs
    dict(name="scout", cls="thief", level=1, weight="light", style="leather", names=("Scout", "del Explorador"),
         head=("Scout Hood", "Capucha del Explorador"),
         pal={"leather": (110, 74, 42), "cloth": (70, 110, 56), "trim": (80, 120, 60), "gem": (130, 200, 100)},
         parts=leather([hood("cloth")], extra=[]), bonus=[eff("jump_boost", 1)], text=("Full set: jump higher", "Set completo: saltas más alto")),
    dict(name="seafarer", cls="thief", level=24, weight="light", style="leather", names=("Seafarer", "del Navegante"),
         head=("Seafarer Hat", "Sombrero del Navegante"),
         pal={"leather": (30, 74, 100), "dark": (30, 40, 60), "trim": (204, 164, 76), "gem": (240, 220, 140), "cloth": (200, 190, 170)},
         parts=leather([tricorn("dark", "trim")], coat=True),
         bonus=[eff("water_breathing"), eff("dolphins_grace", 0, "water")],
         text=("Full set: breathe and swim fast underwater", "Set completo: respiras y nadas rápido bajo el agua")),
    dict(name="berserker", cls="thief", level=30, weight="medium", style="plate", names=("Berserker", "de Berserker"),
         pal={"plate": (128, 128, 134), "trim": (90, 70, 54), "chain": (110, 112, 120), "fur": (196, 186, 170),
              "bone": (226, 214, 184), "gem": (200, 40, 30), "leather": (110, 66, 38)},
         parts=[helmet_shell("plate"), nasal("plate"), horns("bone"), brow("trim"), body_plate("chain"), fur_mantle("fur"),
                belt("leather", "gem"), tassets("leather"), arm_plate("chain", 0.6), spiked_pauldron("plate", "bone"),
                vambrace("leather", "plate"), leg_plate("leather"), knee("plate"), fur_boots("leather", "fur")],
         bonus=[eff("strength", 1, "low_health")], text=("Full set: Strength II while below half health",
                                                             "Set completo: Fuerza II con menos de media vida")),
    dict(name="gear", cls="thief", level=16, weight="light", style="leather", names=("Gearwork", "de Engranajes"),
         head=("Gearwork Goggles", "Gafas de Engranajes"),
         pal={"leather": (96, 62, 36), "trim": (200, 150, 70), "gem": (80, 230, 220), "plate": (170, 124, 56)},
         parts=leather([hood("leather"), goggles("leather", "trim")], extra=[emblem("cog", "trim"), pauldron("plate", "trim", 2, 0.9)]),
         bonus=[eff("speed")], text=("Full set: move faster", "Set completo: te mueves más rápido")),
    dict(name="shadow", cls="thief", level=36, weight="light", style="leather", names=("Shadow", "de las Sombras"),
         head=("Shadow Cowl", "Capucha de las Sombras"),
         pal={"leather": (34, 32, 40), "cloth": (28, 26, 34), "trim": (90, 86, 110), "gem": (180, 60, 60), "dark": (14, 12, 18)},
         parts=leather([hood_deep("cloth", "dark")], coat=True, extra=[cape("cloth")]),
         bonus=[eff("invisibility", 0, "crouching")], text=("Full set: invisible while crouching", "Set completo: invisible agachado")),
    dict(name="wolf_raider", cls="thief", level=40, weight="medium", style="leather", names=("Wolf Raider", "del Saqueador Lobo"),
         head=("Wolf Pelt", "Piel de Lobo"),
         pal={"fur": (150, 146, 140), "leather": (90, 60, 36), "trim": (140, 140, 150), "gem": (240, 200, 60)},
         parts=leather([wolf_head("fur")], fur="fur", extra=[fur_mantle("fur"), emblem("wolf", "trim")]),
         bonus=[eff("speed"), on_kill(heal=2.0)], text=("Full set: move faster, and each kill heals you one heart",
                                                                 "Set completo: te mueves más rápido, y cada muerte te cura un corazón")),
    dict(name="huntsman", cls="thief", level=14, weight="light", style="leather", names=("Huntsman", "del Cazador"),
         head=("Huntsman Hood", "Capucha del Cazador"),
         pal={"leather": (100, 70, 40), "cloth": (50, 90, 44), "trim": (150, 110, 60), "gem": (220, 220, 220), "fur": (150, 110, 70)},
         parts=leather([hood_deep("cloth")], fur="fur", extra=[cape("cloth")]),
         bonus=[eff("night_vision"), eff("jump_boost")], text=("Full set: see in the dark and jump higher", "Set completo: ves en la oscuridad y saltas más alto")),
    dict(name="nightblade", cls="thief", level=74, weight="light", style="leather", names=("Nightblade", "de la Hoja Nocturna"),
         head=("Nightblade Mask", "Máscara de la Hoja Nocturna"),
         pal={"leather": (48, 30, 70), "cloth": (36, 20, 54), "trim": (190, 190, 210), "gem": (200, 120, 255), "dark": (16, 10, 24)},
         parts=leather([hood_deep("cloth", "trim")], coat=True, extra=[emblem("crescent", "trim")]),
         bonus=[on_kill(effect="minecraft:invisibility", amplifier=0, duration=60), eff("strength", 0, "night")],
         text=("Full set: Strength at night, and each kill hides you for 3 seconds",
               "Set completo: Fuerza de noche, y cada muerte te oculta 3 segundos")),
    dict(name="frost_stalker", cls="thief", level=50, weight="medium", style="leather", names=("Frost Stalker", "del Acechador Gélido"),
         head=("Snow Hood", "Capucha de Nieve"),
         pal={"leather": (200, 210, 220), "fur": (240, 244, 248), "trim": (110, 170, 220), "gem": (150, 230, 255)},
         parts=leather([hood("fur")], fur="fur", extra=[fur_mantle("fur"), crystals("gem")]),
         bonus=[{"type": "unfreeze"}, answer("slow"), eff("speed")],
         text=("Full set: swift, the cold never takes you, and whoever strikes you is slowed",
               "Set completo: veloz, el frío nunca te alcanza, y quien te golpea queda ralentizado")),
    dict(name="corsair", cls="thief", level=60, weight="light", style="leather", names=("Corsair", "del Corsario"),
         head=("Corsair Tricorn", "Tricornio del Corsario"),
         pal={"leather": (150, 30, 30), "dark": (30, 26, 30), "trim": (230, 186, 70), "gem": (240, 240, 240), "cloth2": (230, 226, 210)},
         parts=leather([tricorn("dark", "trim")], coat=True, extra=[sash("cloth2"), emblem("skull_emblem", "trim")]),
         bonus=[eff("dolphins_grace", 0, "water"), eff("luck")], text=("Full set: swim fast, and luck is with you",
                                                                       "Set completo: nadas rápido, y la suerte te acompaña")),

    # ------------------------------------------------------------------- the king: Sulthari silks and crowns
    dict(name="brass", cls="king", level=1, weight="medium", style="plate", names=("Brass", "de Latón"),
         pal={"plate": (200, 146, 60), "trim": (60, 200, 190), "gem": (60, 220, 200), "cloth": (170, 40, 40)},
         parts=heavy([helmet_shell("plate"), crest("trim")], mark="sun", big=1.0),
         bonus=[eff("hero_of_the_village")], text=("Full set: the people of the cities honor you",
                                                   "Set completo: la gente de las ciudades te honra")),
    dict(name="sultan", cls="king", level=60, weight="light", style="royal", names=("Sultan", "del Sultán"),
         head=("Sultan Turban", "Turbante del Sultán"),
         pal={"cloth": (240, 236, 224), "cloth2": (170, 30, 40), "trim": (236, 186, 60), "gem": (220, 30, 60), "fur": (250, 250, 246)},
         parts=royal([turban("cloth", "trim", "gem", "cloth2")], mark="crescent", extra=[ermine_cape("cloth2", "fur")]),
         bonus=[eff("hero_of_the_village"), {"type": "absorption", "every": 600}],
         text=("Full set: honored in the cities, and a shield of absorption every 30 seconds",
               "Set completo: honrado en las ciudades, y un escudo de absorción cada 30 segundos")),
    dict(name="vizier", cls="king", level=30, weight="light", style="royal", names=("Vizier", "del Visir"),
         head=("Vizier Hat", "Sombrero del Visir"),
         pal={"cloth": (90, 30, 110), "cloth2": (40, 20, 60), "trim": (230, 186, 80), "gem": (60, 220, 200)},
         parts=royal([janissary_hat("cloth", "trim")], mark="eye_emblem", extra=[high_collar("cloth", "trim")]),
         bonus=[eff("night_vision"), eff("haste")], text=("Full set: see in the dark, and act faster",
                                                              "Set completo: ves en la oscuridad, y actúas más rápido")),
    dict(name="royal_guard", cls="king", level=16, weight="medium", style="plate", names=("Royal Guard", "de la Guardia Real"),
         head=("Janissary Hat", "Gorro de Jenízaro"),
         pal={"plate": (180, 40, 40), "cloth": (240, 236, 224), "trim": (230, 186, 70), "gem": (60, 200, 190)},
         parts=heavy([janissary_hat("cloth", "trim")], plate="plate", big=1.0, mark="crescent", extra=[sash("cloth")]),
         bonus=[eff("resistance", 0, "low_health"), eff("hero_of_the_village")],
         text=("Full set: honored in the cities, and Resistance while below half health",
               "Set completo: honrado en las ciudades, y Resistencia con menos de media vida")),
    dict(name="desert_emir", cls="king", level=14, weight="light", style="royal", names=("Desert Emir", "del Emir del Desierto"),
         head=("Emir Keffiyeh", "Kufiya del Emir"),
         pal={"cloth": (236, 226, 200), "cloth2": (180, 140, 70), "trim": (230, 186, 70), "dark": (30, 26, 24), "gem": (60, 200, 190)},
         parts=royal([keffiyeh("cloth", "dark")], skirt=False, extra=[cape("cloth2")]),
         bonus=[eff("fire_resistance", 0, "day"), eff("speed")], text=("Full set: move faster, and fire cannot touch you by day",
                                                                               "Set completo: te mueves más rápido, y de día el fuego no te toca")),
    dict(name="golden_king", cls="king", level=94, weight="medium", style="plate", names=("Golden King", "del Rey Dorado"),
         head=("Golden Crown", "Corona Dorada"),
         pal={"plate": (232, 186, 60), "trim": (255, 230, 140), "gem": (220, 30, 50), "cloth": (150, 20, 30), "fur": (250, 250, 246)},
         parts=heavy([helmet_shell("plate"), crown("trim", "gem")], big=1.2, mark="sun", extra=[ermine_cape("cloth", "fur")]),
         bonus=[{"type": "absorption", "every": 400}, eff("luck"), eff("hero_of_the_village")],
         text=("Full set: honored and lucky, with a shield of absorption every 20 seconds",
               "Set completo: honrado y con suerte, con un escudo de absorción cada 20 segundos")),
    dict(name="mirage", cls="king", level=40, weight="light", style="royal", names=("Mirage", "del Espejismo"),
         head=("Mirage Veil", "Velo del Espejismo"),
         pal={"cloth": (240, 200, 150), "cloth2": (100, 200, 220), "trim": (240, 210, 120), "gem": (120, 240, 255)},
         parts=royal([hood("cloth"), veil("cloth2"), circlet("trim", "gem")], mark="sun", extra=[cape("cloth2")]),
         bonus=[eff("invisibility", 0, "low_health"), eff("speed")],
         text=("Full set: move faster, and you fade from sight while below half health",
               "Set completo: te mueves más rápido, y te desvaneces con menos de media vida")),
    dict(name="lion_king", cls="king", level=74, weight="medium", style="plate", names=("Lion King", "del Rey León"),
         head=("Lion Mane", "Melena de León"),
         pal={"plate": (210, 160, 60), "fur": (190, 120, 50), "trim": (240, 210, 120), "gem": (220, 40, 40), "cloth": (130, 30, 30)},
         parts=heavy([lion_mane("fur")], big=1.3, mark="lion", cape_mat="cloth"),
         bonus=[eff("strength", 0, "low_health"), answer("knockback", 0.6)],
         text=("Full set: Strength while below half health, and you knock back whoever strikes you",
               "Set completo: Fuerza con menos de media vida, y empujas a quien te golpea")),
    dict(name="peacock", cls="king", level=24, weight="light", style="royal", names=("Peacock", "del Pavo Real"),
         head=("Peacock Turban", "Turbante del Pavo Real"),
         pal={"cloth": (30, 110, 140), "cloth2": (40, 150, 90), "trim": (230, 190, 80), "gem": (60, 90, 220)},
         parts=royal([turban("cloth", "trim", "gem", "cloth2")], mark="peacock", extra=[cape("cloth2")]),
         bonus=[eff("hero_of_the_village"), eff("jump_boost")], text=("Full set: honored in the cities, and you jump higher",
                                                                "Set completo: honrado en las ciudades, y saltas más alto")),
    dict(name="pharaoh", cls="king", level=84, weight="medium", style="royal", names=("Pharaoh", "del Faraón"),
         head=("Pharaoh Nemes", "Nemes del Faraón"),
         pal={"cloth": (240, 232, 210), "plate": (232, 186, 60), "trim": (232, 186, 60), "trim2": (40, 70, 170), "gem": (40, 90, 210)},
         parts=royal([nemes("trim", "trim2"), uraeus("trim", "gem")], mark="ankh", extra=[gorget("trim"), pauldron("trim", "trim2", 2, 1.0)]),
         bonus=[{"type": "cleanse", "effects": ["minecraft:wither"]}, eff("regeneration", 0, "low_health")],
         text=("Full set: wither does not take hold, and you regenerate while below half health",
               "Set completo: la descomposición no te afecta, y te regeneras con menos de media vida")),
]

# the unique armor pieces (droppable Relics): one piece each, with its own model
UNIQUES = [
    dict(name="crown_of_five_sultans", piece="helmet",
         pal={"plate": (232, 186, 60), "trim": (255, 230, 140), "gem": (220, 30, 60), "cloth": (240, 236, 224)},
         parts=[turban("cloth", "trim", "gem", "trim"), crown("trim", "gem")]),
    dict(name="white_wolf_mantle", piece="chestplate",
         pal={"fur": (240, 244, 248), "leather": (150, 156, 170), "trim": (110, 170, 220), "gem": (150, 220, 255)},
         parts=[body_plate("leather", 1.0), fur_mantle("fur"), arm_plate("leather", 0.6), pauldron("fur", "trim", 2, 1.2),
                [Cube("armorBody", (-4.5, 12, 2.6), (9, 12, 1), "fur", 0.2, rot=[4, 0, 0], pivot=[0, 24, 3])]]),
    dict(name="caravan_treads", piece="boots",
         pal={"leather": (130, 88, 48), "trim": (60, 200, 190), "cloth": (200, 170, 120)}, parts=[curled_shoes("leather", "trim"), wraps("cloth")]),
    dict(name="undying_wrappings", piece="leggings",
         pal={"cloth": (206, 196, 168), "trim": (30, 150, 140)}, parts=[leg_plate("cloth", 0.6), knee("trim")]),
    dict(name="blind_judge_helm", piece="helmet",
         pal={"plate": (210, 214, 226), "trim": (232, 186, 70), "cloth": (40, 40, 60), "gem": (230, 230, 240)},
         parts=[great_helm("plate", "trim"), halo("trim"), [Cube("armorHead", (-4.2, 28, -5.6), (8, 2, 1), "cloth", 0.1)]]),
    dict(name="furnace_heart", piece="chestplate",
         pal={"plate": (60, 22, 14), "trim": (255, 150, 50), "gem": (255, 200, 80), "bone": (40, 30, 30)},
         parts=[body_plate("plate"), breastplate("plate", "flame"), gorget("trim"), arm_plate("plate"), spiked_pauldron("plate", "bone", "trim"),
                flames("gem"), vambrace("plate", "trim")]),
]
