"""The skill trees, Diablo II style: 30 skills per class in three branches of 10. The 10 base skills of
docs/Clases.md, plus 20 upgrades per class. Upgrades are passives of two kinds:
  - synergies: each rank raises numbers of the skills they improve ("<value>_bonus": x per rank multiplies the
    value by 1 + x * rank; "<value>_add": adds x per rank; "cost_cut" and "cooldown_cut" lower them);
  - changes: the improved skill's code checks the upgrade's rank and does something new (a burst, a second axe).
scripts/make_skill_tree.py writes the catalog block of SkillCatalog.java, the values, the names and the icons.

Each entry: id, type (active, passive, ultimate), level, parent, tab, column, upgrades (the skills it improves),
values, (en name, es name), (en description, es description). Base skills keep their own names and descriptions.
"""


def base(id, type, level, parent, tab, column):
    return dict(id=id, type=type, level=level, parent=parent, tab=tab, column=column, upgrades=[], values=None, names=None, desc=None)


def up(id, level, parent, tab, column, upgrades, values, names, desc):
    return dict(id=id, type="passive", level=level, parent=parent, tab=tab, column=column, upgrades=upgrades, values=values, names=names, desc=desc)


BRANCHES = {
    "knight": [("Strike and Charge", "Golpe y Carga"), ("Shield and Oath", "Escudo y Juramento"), ("Banner and Verdict", "Estandarte y Veredicto")],
    "necromancer": [("Judgment", "Juicio"), ("The Bound Dead", "Los Muertos Atados"), ("Wraps and Plagues", "Vendas y Plagas")],
    "sorceress": [("Fire", "Fuego"), ("Frost", "Escarcha"), ("Storm and Stars", "Tormenta y Estrellas")],
    "thief": [("Blades", "Hojas"), ("Thieving and Throwing", "Robo y Lanzamiento"), ("Smoke and Traps", "Humo y Trampas")],
    "king": [("Command", "Mando"), ("Decrees", "Decretos"), ("Guard and Treasury", "Guardia y Tesoro")],
}

TREES = {
    "knight": [
        base("scale_strike", "active", 1, None, 0, 1),
        up("weighted_blade", 6, "scale_strike", 0, 0, ["scale_strike"], {"damage_bonus": 0.12}, ("Weighted Blade", "Hoja Lastrada"),
           ("+12% Scale Strike damage per rank", "+12% de daño de Golpe de Balanza por rango")),
        up("rending_strike", 6, "scale_strike", 0, 2, ["scale_strike"], {"bleed_s_add": 1}, ("Rending Strike", "Golpe Desgarrador"),
           ("Scale Strike makes the enemy bleed (1 s per rank)", "Golpe de Balanza hace sangrar al enemigo (1 s por rango)")),
        base("legionary_charge", "active", 11, "scale_strike", 0, 1),
        up("cavalry_drill", 16, "legionary_charge", 0, 0, ["legionary_charge"], {"distance_add": 1, "damage_bonus": 0.1},
           ("Cavalry Drill", "Instrucción de Caballería"), ("Legionary Charge goes 1 block farther and hits 10% harder per rank",
                                                           "Carga Legionaria llega 1 bloque más lejos y pega un 10% más por rango")),
        up("trampling_charge", 16, "legionary_charge", 0, 2, ["legionary_charge"], {"damage": 4}, ("Trampling Charge", "Carga Arrolladora"),
           ("Legionary Charge ends in a shockwave round you (4 damage per rank)", "Carga Legionaria termina en una onda de choque a tu alrededor (4 de daño por rango)")),
        up("relentless_advance", 21, "cavalry_drill", 0, 0, ["legionary_charge"], {"cooldown_cut": 0.08, "cost_cut": 0.05},
           ("Relentless Advance", "Avance Implacable"), ("Legionary Charge: 8% less cooldown and 5% less cost per rank",
                                                         "Carga Legionaria: 8% menos de enfriamiento y 5% menos de costo por rango")),
        up("executioners_edge", 21, "rending_strike", 0, 2, ["scale_strike"], {"execute_bonus": 0.15}, ("Executioner's Edge", "Filo del Verdugo"),
           ("Scale Strike hits enemies under 30% health 15% harder per rank", "Golpe de Balanza pega un 15% más por rango a enemigos con menos del 30% de vida")),
        up("charge_mastery", 26, "trampling_charge", 0, 1, [], {"damage_bonus": 0.04}, ("Charge Mastery", "Maestría de Carga"),
           ("Charge Stance: 4% more damage per rank", "Postura de Carga: 4% más de daño por rango")),
        up("wrath_of_the_scale", 26, "executioners_edge", 0, 2, ["scale_strike"], {"max_bonus_add": 0.2}, ("Wrath of the Scale", "Ira de la Balanza"),
           ("Scale Strike's bonus for the enemy's extra health can grow 20% higher per rank", "La bonificación de Golpe de Balanza por la vida extra del enemigo crece un 20% más por rango")),

        base("shield_wall", "active", 1, None, 1, 1),
        up("tower_shield", 6, "shield_wall", 1, 0, ["shield_wall"], {"duration_s_add": 0.5}, ("Tower Shield", "Escudo Torre"),
           ("Shield Wall lasts 0.5 s longer per rank", "Muro de Escudos dura 0.5 s más por rango")),
        up("shield_bash", 6, "shield_wall", 1, 2, ["shield_wall"], {"damage": 3}, ("Shield Bash", "Embestida de Escudo"),
           ("Shield Wall ends with a bash that throws back and stuns those in front (3 damage per rank)",
            "Muro de Escudos termina con una embestida que empuja y aturde a los de enfrente (3 de daño por rango)")),
        base("iron_discipline", "passive", 11, "shield_wall", 1, 0),
        base("protectors_oath", "active", 11, "shield_wall", 1, 1),
        up("sworn_guardian", 16, "protectors_oath", 1, 2, ["protectors_oath"], {"duration_s_add": 1, "absorb_add": 0.03},
           ("Sworn Guardian", "Guardián Juramentado"), ("Protector's Oath lasts 1 s longer and takes 3% more of each blow per rank",
                                                         "Juramento del Protector dura 1 s más y absorbe un 3% más de cada golpe por rango")),
        base("contained_wrath", "passive", 21, "iron_discipline", 1, 0),
        base("living_rampart", "active", 21, "protectors_oath", 1, 1),
        up("bulwark_of_aureum", 26, "living_rampart", 1, 2, ["living_rampart"], {"width_add": 1, "duration_s_add": 1},
           ("Bulwark of Aureum", "Baluarte de Aureum"), ("Living Rampart is 1 block wider and stands 1 s longer per rank",
                                                         "Muralla Viviente es 1 bloque más ancha y dura 1 s más por rango")),
        base("last_one_standing", "ultimate", 30, "living_rampart", 1, 1),

        base("banner_cry", "active", 1, None, 2, 1),
        up("rallying_call", 6, "banner_cry", 2, 0, ["banner_cry"], {"strength_s": 2}, ("Rallying Call", "Llamada a Filas"),
           ("Banner Cry gives you and your allies Strength (2 s per rank)", "Grito del Estandarte te da Fuerza a ti y a tus aliados (2 s por rango)")),
        up("banner_of_the_order", 6, "banner_cry", 2, 2, ["banner_cry"], {"radius_add": 1.5}, ("Banner of the Order", "Estandarte de la Orden"),
           ("Banner Cry reaches 1.5 blocks farther per rank", "Grito del Estandarte llega 1.5 bloques más lejos por rango")),
        base("verdict", "active", 11, "banner_cry", 2, 1),
        up("wide_judgment", 16, "verdict", 2, 0, ["verdict"], {"radius_add": 0.6}, ("Wide Judgment", "Juicio Amplio"),
           ("Verdict reaches 0.6 blocks farther per rank", "Veredicto llega 0.6 bloques más lejos por rango")),
        up("heavy_verdict", 16, "verdict", 2, 2, ["verdict"], {"damage_bonus": 0.12}, ("Heavy Verdict", "Veredicto Pesado"),
           ("+12% Verdict damage per rank", "+12% de daño de Veredicto por rango")),
        up("martyrs_resolve", 21, "rallying_call", 2, 0, ["banner_cry"], {"resolve_per_enemy": 2}, ("Martyr's Resolve", "Determinación del Mártir"),
           ("Banner Cry gives 2 Resolve per enemy it taunts, per rank", "Grito del Estandarte da 2 de Determinación por enemigo provocado, por rango")),
        up("sentence_of_the_scale", 21, "heavy_verdict", 2, 2, ["verdict"], {"stun_s_add": 0.3}, ("Sentence of the Scale", "Sentencia de la Balanza"),
           ("Verdict stuns 0.3 s longer per rank", "Veredicto aturde 0.3 s más por rango")),
        up("oathbound_voice", 26, "martyrs_resolve", 2, 0, ["banner_cry"], {"cooldown_cut": 0.06, "cost_cut": 0.06}, ("Oathbound Voice", "Voz Juramentada"),
           ("Banner Cry: 6% less cooldown and cost per rank", "Grito del Estandarte: 6% menos de enfriamiento y costo por rango")),
        up("war_banner", 26, "sentence_of_the_scale", 2, 2, ["verdict"], {"banner_s": 2}, ("War Banner", "Estandarte de Guerra"),
           ("Verdict plants a banner that weakens enemies near it (2 s per rank)", "Veredicto planta un estandarte que debilita a los enemigos cercanos (2 s por rango)")),
    ],
    "necromancer": [
        base("threshold_touch", "active", 1, None, 0, 1),
        up("soul_siphon", 6, "threshold_touch", 0, 0, ["threshold_touch"], {"drain_add": 0.1, "damage_bonus": 0.1}, ("Soul Siphon", "Sifón de Almas"),
           ("Threshold Touch drains 10% more and hits 10% harder per rank", "Toque del Umbral drena un 10% más y pega un 10% más por rango")),
        up("lingering_mark", 6, "threshold_touch", 0, 2, ["threshold_touch"], {"slow_s": 1}, ("Lingering Mark", "Marca Persistente"),
           ("Threshold Touch slows the enemy (1 s per rank)", "Toque del Umbral ralentiza al enemigo (1 s por rango)")),
        base("scales_of_anubet", "active", 11, "threshold_touch", 0, 1),
        up("final_rites", 16, "scales_of_anubet", 0, 0, ["scales_of_anubet"], {"souls_add": 1}, ("Final Rites", "Ritos Finales"),
           ("An enemy executed by the Scales leaves 1 more soul per rank", "Un enemigo ejecutado por la Balanza deja 1 alma más por rango")),
        up("weighed_heart", 16, "scales_of_anubet", 0, 2, ["scales_of_anubet"], {"threshold_add": 0.03}, ("Weighed Heart", "Corazón Pesado"),
           ("The Scales execute at 3% more health per rank", "La Balanza ejecuta con un 3% más de vida por rango")),
        up("devouring_beam", 21, "soul_siphon", 0, 0, ["threshold_touch"], {"chain": 1}, ("Devouring Beam", "Haz Devorador"),
           ("Threshold Touch jumps to another enemy (1 more per rank)", "Toque del Umbral salta a otro enemigo (1 más por rango)")),
        up("judges_gaze", 21, "lingering_mark", 0, 2, ["threshold_touch"], {"range_add": 1.5, "cost_cut": 0.06}, ("Judge's Gaze", "Mirada del Juez"),
           ("Threshold Touch reaches 1.5 blocks farther and costs 6% less per rank", "Toque del Umbral llega 1.5 bloques más lejos y cuesta un 6% menos por rango")),
        up("soul_harvest", 26, "final_rites", 0, 0, [], {"max_souls_add": 1}, ("Soul Harvest", "Cosecha de Almas"),
           ("You can hold 1 more soul per rank", "Puedes guardar 1 alma más por rango")),
        up("verdict_of_anubet", 26, "weighed_heart", 0, 2, ["scales_of_anubet"], {"damage_bonus": 0.15, "cooldown_cut": 0.06},
           ("Verdict of Anubet", "Veredicto de Anubet"), ("The Scales hit 15% harder and come back 6% sooner per rank",
                                                          "La Balanza pega un 15% más y se recarga un 6% antes por rango")),

        base("clay_warden", "active", 1, None, 1, 1),
        up("baked_clay", 6, "clay_warden", 1, 0, ["clay_warden"], {"health_add": 6, "golem_damage_add": 1.5}, ("Baked Clay", "Arcilla Cocida"),
           ("Clay Wardens have 6 more health and hit 1.5 harder per rank", "Los Guardianes de Arcilla tienen 6 de vida más y pegan 1.5 más por rango")),
        dict(id="raise_the_embalmed", type="active", level=6, parent="clay_warden", tab=1, column=2, upgrades=[],
             values={"cost": 20, "cooldown_s": 6, "count": 2, "max_dead": 6, "duration_s": 20, "health": 16, "dead_damage": 4},
             names=("Raise the Embalmed", "Alzar a los Embalsamados"),
             desc=("Two linen-wrapped dead claw out of the sand and fight for you for 20 seconds (up to 6)",
                   "Dos muertos envueltos en lino salen de la arena y luchan por ti 20 segundos (hasta 6)")),
        base("rite_of_passage", "passive", 11, "clay_warden", 1, 0),
        base("canopic_jars", "active", 11, "clay_warden", 1, 1),
        up("embalming_salts", 16, "raise_the_embalmed", 1, 2, ["raise_the_embalmed"], {"health_add": 6, "count_add": 0.25},
           ("Embalming Salts", "Sales de Embalsamar"), ("The Embalmed have 6 more health per rank, and rise one more at rank 4",
                                                        "Los Embalsamados tienen 6 de vida más por rango, y se alza uno más en rango 4")),
        base("heavy_heart", "passive", 21, "rite_of_passage", 1, 0),
        up("legion_of_clay", 21, "canopic_jars", 1, 1, ["clay_warden"], {"max_wardens_add": 0.4}, ("Legion of Clay", "Legión de Arcilla"),
           ("More Clay Wardens at once (2 more at rank 5)", "Más Guardianes de Arcilla a la vez (2 más en rango 5)")),
        up("linen_of_eternity", 21, "embalming_salts", 1, 2, ["raise_the_embalmed", "clay_warden"], {"duration_s_add": 4, "max_dead_add": 0.4},
           ("Linen of Eternity", "Lino de la Eternidad"), ("Your Embalmed and Clay Wardens last 4 s longer per rank, and more Embalmed can stand (2 more at rank 5)",
                                                           "Tus Embalsamados y Guardianes duran 4 s más por rango, y pueden estar más Embalsamados (2 más en rango 5)")),
        up("jackal_fury", 26, "linen_of_eternity", 1, 2, ["raise_the_embalmed"], {"dead_damage_add": 1.5, "cooldown_cut": 0.05},
           ("Jackal Fury", "Furia del Chacal"), ("The Embalmed hit 1.5 harder per rank, and you raise them 5% sooner",
                                                 "Los Embalsamados pegan 1.5 más por rango, y los alzas un 5% antes")),

        base("burial_wraps", "active", 1, None, 2, 1),
        up("tight_wraps", 6, "burial_wraps", 2, 0, ["burial_wraps"], {"root_s_add": 0.5}, ("Tight Wraps", "Vendas Apretadas"),
           ("Burial Wraps hold 0.5 s longer per rank", "Vendas Funerarias retienen 0.5 s más por rango")),
        up("mummify", 6, "burial_wraps", 2, 2, ["burial_wraps"], {"damage": 1.5}, ("Mummify", "Momificar"),
           ("Wrapped enemies take 1.5 damage each second per rank", "Los enemigos vendados reciben 1.5 de daño por segundo por rango")),
        base("scarab_plague", "active", 11, "burial_wraps", 2, 1),
        up("swarm_queen", 16, "scarab_plague", 2, 0, ["scarab_plague"], {"jumps_add": 1, "damage_bonus": 0.1}, ("Swarm Queen", "Reina del Enjambre"),
           ("Scarab Plague jumps once more and bites 10% harder per rank", "Plaga de Escarabajos salta una vez más y muerde un 10% más por rango")),
        up("locust_cloud", 16, "scarab_plague", 2, 2, ["scarab_plague"], {"slow_level": 1}, ("Locust Cloud", "Nube de Langostas"),
           ("Scarab Plague also slows its victim (stronger with rank)", "Plaga de Escarabajos también ralentiza a su víctima (más con el rango)")),
        base("boat_of_the_dead", "active", 21, "scarab_plague", 2, 1),
        up("the_ferrymans_toll", 26, "boat_of_the_dead", 2, 0, ["boat_of_the_dead"], {"damage_bonus": 0.15, "width_add": 0.5},
           ("The Ferryman's Toll", "El Peaje del Barquero"), ("Boat of the Dead hits 15% harder and is 0.5 blocks wider per rank",
                                                              "Barca de los Muertos pega un 15% más y es 0.5 bloques más ancha por rango")),
        up("tide_of_the_underworld", 26, "boat_of_the_dead", 2, 2, ["the_great_judgment"], {"duration_s_add": 1, "radius_add": 0.5},
           ("Tide of the Underworld", "Marea del Inframundo"), ("The Great Judgment stays open 1 s longer and 0.5 blocks wider per rank",
                                                                "El Gran Juicio dura 1 s más abierto y es 0.5 bloques más ancho por rango")),
        base("the_great_judgment", "ultimate", 30, "boat_of_the_dead", 2, 1),
    ],
    "sorceress": [
        base("ember_verse", "active", 1, None, 0, 1),
        up("kindled_verse", 6, "ember_verse", 0, 0, ["ember_verse"], {"damage_bonus": 0.12}, ("Kindled Verse", "Verso Avivado"),
           ("+12% Ember Verse damage per rank", "+12% de daño de Verso de Ascuas por rango")),
        up("cinder_burst", 6, "ember_verse", 0, 2, ["ember_verse"], {"burst": 0.25}, ("Cinder Burst", "Estallido de Ceniza"),
           ("Ember Verse bursts where it lands (25% of its damage per rank around it)", "Verso de Ascuas estalla al impactar (25% de su daño por rango alrededor)")),
        base("burning_calligraphy", "active", 11, "ember_verse", 0, 1),
        up("double_stroke", 16, "burning_calligraphy", 0, 0, ["burning_calligraphy"], {"cross": 1}, ("Double Stroke", "Doble Trazo"),
           ("Burning Calligraphy writes a second line across the first", "Caligrafía Ardiente escribe una segunda línea cruzada")),
        up("searing_ink", 16, "burning_calligraphy", 0, 2, ["burning_calligraphy"], {"damage_bonus": 0.15, "duration_s_add": 1}, ("Searing Ink", "Tinta Abrasadora"),
           ("Burning Calligraphy burns 15% harder and 1 s longer per rank", "Caligrafía Ardiente quema un 15% más y dura 1 s más por rango")),
        up("phoenix_verse", 21, "kindled_verse", 0, 0, ["ember_verse"], {"extra_bolts": 1}, ("Phoenix Verse", "Verso del Fénix"),
           ("Ember Verse also strikes another enemy near the first (1 more per rank)", "Verso de Ascuas también golpea a otro enemigo cercano (1 más por rango)")),
        up("wildfire", 21, "cinder_burst", 0, 2, ["ember_verse"], {"burn_s_add": 1}, ("Wildfire", "Fuego Salvaje"),
           ("Ember Verse burns 1 s longer per rank", "Verso de Ascuas quema 1 s más por rango")),
        up("fire_mastery", 26, "double_stroke", 0, 0, ["ember_verse", "burning_calligraphy"], {"damage_bonus": 0.08}, ("Fire Mastery", "Maestría del Fuego"),
           ("+8% damage to Ember Verse and Burning Calligraphy per rank", "+8% de daño a Verso de Ascuas y Caligrafía Ardiente por rango")),
        up("solar_script", 26, "searing_ink", 0, 2, ["burning_calligraphy"], {"length_add": 2}, ("Solar Script", "Escritura Solar"),
           ("Burning Calligraphy writes 2 blocks longer per rank", "Caligrafía Ardiente escribe 2 bloques más larga por rango")),

        base("frost_lance", "active", 1, None, 1, 1),
        up("piercing_cold", 6, "frost_lance", 1, 0, ["frost_lance"], {"damage_bonus": 0.12}, ("Piercing Cold", "Frío Penetrante"),
           ("+12% Frost Lance damage per rank", "+12% de daño de Lanza de Escarcha por rango")),
        up("shatter", 6, "frost_lance", 1, 2, ["frost_lance"], {"shatter_bonus": 0.1}, ("Shatter", "Quebrar"),
           ("Frost Lance hits slowed enemies 10% harder per rank", "Lanza de Escarcha pega un 10% más por rango a enemigos ralentizados")),
        base("water_mirror", "active", 11, "frost_lance", 1, 1),
        up("deep_freeze", 16, "piercing_cold", 1, 0, ["frost_lance"], {"slow_s_add": 0.5}, ("Deep Freeze", "Congelación Profunda"),
           ("Frost Lance slows 0.5 s longer per rank", "Lanza de Escarcha ralentiza 0.5 s más por rango")),
        up("long_stride", 16, "water_mirror", 1, 1, ["water_mirror"], {"distance_add": 1.5, "cooldown_cut": 0.05}, ("Long Stride", "Zancada Larga"),
           ("Water Mirror goes 1.5 blocks farther and comes back 5% sooner per rank", "Espejo de Agua llega 1.5 bloques más lejos y se recarga un 5% antes por rango")),
        up("mirror_shards", 16, "water_mirror", 1, 2, ["water_mirror"], {"damage": 3}, ("Mirror Shards", "Esquirlas del Espejo"),
           ("Water Mirror bursts in ice where you stood (3 damage per rank)", "Espejo de Agua estalla en hielo donde estabas (3 de daño por rango)")),
        up("glacial_spike", 21, "deep_freeze", 1, 0, ["frost_lance"], {"pierce": 1}, ("Glacial Spike", "Púa Glacial"),
           ("Frost Lance pierces through to more enemies (1 more per rank)", "Lanza de Escarcha atraviesa a más enemigos (1 más por rango)")),
        up("frost_mastery", 26, "long_stride", 1, 1, ["frost_lance", "water_mirror"], {"damage_bonus": 0.06, "cost_cut": 0.04},
           ("Frost Mastery", "Maestría de la Escarcha"), ("Frost Lance hits 6% harder, and both frost spells cost 4% less, per rank",
                                                          "Lanza de Escarcha pega un 6% más y ambos hechizos de escarcha cuestan un 4% menos, por rango")),
        up("lingering_reflection", 26, "mirror_shards", 1, 2, ["water_mirror"], {"clone_s_add": 1}, ("Lingering Reflection", "Reflejo Persistente"),
           ("The ice clone lasts 1 s longer per rank", "El clon de hielo dura 1 s más por rango")),

        base("wandering_spark", "active", 1, None, 2, 1),
        up("forked_spark", 6, "wandering_spark", 2, 0, ["wandering_spark"], {"bounces_add": 0.5}, ("Forked Spark", "Chispa Bifurcada"),
           ("Wandering Spark bounces more (2 more at rank 4)", "Chispa Errante rebota más (2 más en rango 4)")),
        up("static_field", 6, "wandering_spark", 2, 2, ["wandering_spark"], {"shock_s": 0.5}, ("Static Field", "Campo Estático"),
           ("Wandering Spark stuns what it strikes (0.5 s per rank)", "Chispa Errante aturde a lo que golpea (0.5 s por rango)")),
        base("sky_map", "passive", 11, "wandering_spark", 2, 0),
        base("petal_tempest", "active", 11, "wandering_spark", 2, 1),
        up("thorned_petals", 16, "petal_tempest", 2, 2, ["petal_tempest"], {"damage_bonus": 0.15, "radius_add": 0.4}, ("Thorned Petals", "Pétalos Espinosos"),
           ("Petal Tempest cuts 15% harder and 0.4 blocks wider per rank", "Tempestad de Pétalos corta un 15% más y es 0.4 bloques más ancha por rango")),
        base("arcane_poetry", "passive", 21, "sky_map", 2, 0),
        base("starfall", "active", 21, "petal_tempest", 2, 1),
        up("falling_heavens", 26, "starfall", 2, 2, ["starfall"], {"stars_add": 0.6, "damage_bonus": 0.08}, ("Falling Heavens", "Cielos que Caen"),
           ("Starfall drops more stars (3 more at rank 5) that hit 8% harder per rank", "Lluvia de Estrellas deja caer más estrellas (3 más en rango 5) que pegan un 8% más por rango")),
        base("written_eclipse", "ultimate", 30, "starfall", 2, 1),
    ],
    "thief": [
        base("double_edge", "active", 1, None, 0, 1),
        up("quick_hands", 6, "double_edge", 0, 0, ["double_edge"], {"damage_bonus": 0.12}, ("Quick Hands", "Manos Rápidas"),
           ("+12% Double Edge damage per rank", "+12% de daño de Doble Filo por rango")),
        up("third_edge", 6, "double_edge", 0, 2, ["double_edge"], {"third": 1}, ("Third Edge", "Tercer Filo"),
           ("Double Edge strikes a third time, and leaves a third Mark", "Doble Filo golpea una tercera vez y deja una tercera Marca")),
        base("cutthroat", "active", 11, "double_edge", 0, 1),
        up("butchers_arithmetic", 16, "cutthroat", 0, 0, ["cutthroat"], {"per_mark_add": 0.05}, ("Butcher's Arithmetic", "Aritmética del Carnicero"),
           ("Cutthroat gains 5% more per Mark per rank", "Degollador gana un 5% más por Marca por rango")),
        up("open_artery", 16, "cutthroat", 0, 2, ["cutthroat"], {"bleed_s": 1.5}, ("Open Artery", "Arteria Abierta"),
           ("Cutthroat on 3 or more Marks makes the enemy bleed (1.5 s per rank)", "Degollador con 3 o más Marcas hace sangrar al enemigo (1.5 s por rango)")),
        base("thousand_cuts", "active", 21, "cutthroat", 0, 1),
        up("whirling_steel", 26, "thousand_cuts", 0, 0, ["thousand_cuts"], {"targets_add": 0.4, "damage_bonus": 0.1}, ("Whirling Steel", "Acero Giratorio"),
           ("Thousand Cuts reaches more enemies (2 more at rank 5) and cuts 10% harder per rank",
            "Mil Cortes alcanza más enemigos (2 más en rango 5) y corta un 10% más por rango")),
        up("master_thief", 26, "thousand_cuts", 0, 2, ["the_great_heist"], {"duration_s_add": 1}, ("Master Thief", "Maestro Ladrón"),
           ("The Great Heist lasts 1 s longer per rank", "El Gran Golpe dura 1 s más por rango")),
        base("the_great_heist", "ultimate", 30, "thousand_cuts", 0, 1),

        base("light_fingers", "active", 1, None, 1, 1),
        up("pickpocket", 6, "light_fingers", 1, 0, ["light_fingers"], {"cooldown_cut": 0.1, "range_add": 1}, ("Pickpocket", "Carterista"),
           ("Light Fingers comes back 10% sooner and reaches 1 block farther per rank", "Dedos Ligeros se recarga un 10% antes y llega 1 bloque más lejos por rango")),
        up("sleight_of_hand", 6, "light_fingers", 1, 2, ["light_fingers"], {"marks": 1}, ("Sleight of Hand", "Juego de Manos"),
           ("Light Fingers also leaves Marks on its victim (1 per rank)", "Dedos Ligeros también deja Marcas en su víctima (1 por rango)")),
        base("deep_pockets", "passive", 11, "light_fingers", 1, 0),
        base("throwing_axe", "active", 11, "light_fingers", 1, 1),
        up("twin_axes", 16, "throwing_axe", 1, 1, ["throwing_axe"], {"twin": 1}, ("Twin Axes", "Hachas Gemelas"),
           ("Throwing Axe throws a second axe beside the first", "Hacha Arrojadiza lanza una segunda hacha junto a la primera")),
        up("keen_axe", 16, "throwing_axe", 1, 2, ["throwing_axe"], {"damage_bonus": 0.12, "range_add": 1}, ("Keen Axe", "Hacha Afilada"),
           ("Throwing Axe cuts 12% harder and flies 1 block farther per rank", "Hacha Arrojadiza corta un 12% más y vuela 1 bloque más lejos por rango")),
        base("scavengers_instinct", "passive", 21, "deep_pockets", 1, 0),
        up("the_fences_cut", 26, "deep_pockets", 1, 1, ["deep_pockets"], {"gold_bonus_add": 0.1, "double_chance_add": 0.02},
           ("The Fence's Cut", "La Parte del Perista"), ("Deep Pockets: 10% more Dinars and 2% more double loot per rank",
                                                         "Bolsillos Profundos: 10% más de dinares y 2% más de botín doble por rango")),
        up("ambusher", 26, "scavengers_instinct", 1, 0, ["scavengers_instinct"], {"backstab_add": 0.1}, ("Ambusher", "Emboscador"),
           ("Blows from behind hit 10% harder per rank", "Los golpes por la espalda pegan un 10% más por rango")),

        base("smoke_step", "active", 1, None, 2, 1),
        up("thick_smoke", 6, "smoke_step", 2, 0, ["smoke_step"], {"duration_s_add": 0.5}, ("Thick Smoke", "Humo Espeso"),
           ("Smoke Step hides you 0.5 s longer per rank", "Paso de Humo te oculta 0.5 s más por rango")),
        up("choking_smoke", 6, "smoke_step", 2, 2, ["smoke_step"], {"blind_s": 1}, ("Choking Smoke", "Humo Asfixiante"),
           ("Smoke Step blinds the enemies around you (1 s per rank)", "Paso de Humo ciega a los enemigos cercanos (1 s por rango)")),
        base("fjord_snare", "active", 11, "smoke_step", 2, 1),
        up("line_of_snares", 16, "fjord_snare", 2, 0, ["fjord_snare"], {"extra_snares": 1}, ("Line of Snares", "Línea de Trampas"),
           ("Fjord Snare sets more traps beside the first (1 more per rank)", "Trampa del Fiordo coloca más trampas junto a la primera (1 más por rango)")),
        up("barbed_rope", 16, "fjord_snare", 2, 2, ["fjord_snare"], {"damage_bonus": 0.2, "bleed_s_add": 1}, ("Barbed Rope", "Cuerda con Púas"),
           ("Fjord Snare hurts 20% more and bleeds 1 s longer per rank", "Trampa del Fiordo hiere un 20% más y hace sangrar 1 s más por rango")),
        up("ash_cloak", 21, "thick_smoke", 2, 0, ["smoke_step"], {"strength": 1}, ("Ash Cloak", "Manto de Ceniza"),
           ("While hidden by Smoke Step you gain Strength", "Mientras Paso de Humo te oculta ganas Fuerza")),
        up("shadow_walker", 21, "choking_smoke", 2, 2, ["smoke_step"], {"cooldown_cut": 0.08}, ("Shadow Walker", "Caminante de Sombras"),
           ("Smoke Step comes back 8% sooner per rank", "Paso de Humo se recarga un 8% antes por rango")),
        up("hunters_patience", 26, "line_of_snares", 2, 0, ["fjord_snare"], {"root_s_add": 0.5, "duration_s_add": 10}, ("Hunter's Patience", "Paciencia del Cazador"),
           ("Fjord Snare holds 0.5 s longer and waits 10 s longer per rank", "Trampa del Fiordo retiene 0.5 s más y espera 10 s más por rango")),
        up("master_of_the_fjords", 26, "barbed_rope", 2, 2, ["fjord_snare"], {"cooldown_cut": 0.08, "cost_cut": 0.06},
           ("Master of the Fjords", "Señor de los Fiordos"), ("Fjord Snare: 8% less cooldown and 6% less cost per rank",
                                                              "Trampa del Fiordo: 8% menos de enfriamiento y 6% menos de costo por rango")),
    ],
    "king": [
        base("scepter_slash", "active", 1, None, 0, 1),
        up("royal_edge", 6, "scepter_slash", 0, 0, ["scepter_slash"], {"damage_bonus": 0.12}, ("Royal Edge", "Filo Real"),
           ("+12% Scepter Slash damage per rank", "+12% de daño de Tajo del Cetro por rango")),
        up("tribute", 6, "scepter_slash", 0, 2, ["scepter_slash"], {"authority_add": 1.5}, ("Tribute", "Tributo"),
           ("Scepter Slash gives 1.5 more Authority per rank", "Tajo del Cetro da 1.5 de Autoridad más por rango")),
        base("command", "active", 11, "scepter_slash", 0, 1),
        up("sweeping_scepter", 16, "royal_edge", 0, 0, ["scepter_slash"], {"sweep": 0.3}, ("Sweeping Scepter", "Cetro Barredor"),
           ("Scepter Slash also cuts the enemies beside the target (30% per rank)", "Tajo del Cetro también corta a los enemigos junto al objetivo (30% por rango)")),
        up("rally_the_court", 16, "command", 0, 1, ["command"], {"speed_s": 2}, ("Rally the Court", "Reúne a la Corte"),
           ("Command quickens you and your allies (2 s per rank)", "Mando te acelera a ti y a tus aliados (2 s por rango)")),
        up("marked_for_death", 16, "command", 0, 2, ["command"], {"duration_s_add": 1}, ("Marked for Death", "Marcado para Morir"),
           ("Command lasts 1 s longer per rank", "Mando dura 1 s más por rango")),
        up("sultans_wrath", 21, "sweeping_scepter", 0, 0, ["scepter_slash"], {"damage_bonus": 0.1, "range_add": 0.5}, ("Sultan's Wrath", "Ira del Sultán"),
           ("Scepter Slash hits 10% harder and reaches 0.5 blocks farther per rank", "Tajo del Cetro pega un 10% más y llega 0.5 bloques más lejos por rango")),
        up("authority_of_the_crown", 26, "rally_the_court", 0, 1, [], {"authority_per_kill": 2}, ("Authority of the Crown", "Autoridad de la Corona"),
           ("Each kill gives 2 more Authority per rank", "Cada muerte da 2 de Autoridad más por rango")),
        up("order_of_execution", 26, "marked_for_death", 0, 2, ["command"], {"damage_bonus": 0.05}, ("Order of Execution", "Orden de Ejecución"),
           ("The commanded enemy takes 5% more damage per rank", "El enemigo señalado recibe un 5% más de daño por rango")),

        base("decree_of_steadfastness", "active", 1, None, 1, 1),
        up("iron_decree", 6, "decree_of_steadfastness", 1, 0, ["decree_of_steadfastness"], {"regen": 1}, ("Iron Decree", "Decreto de Hierro"),
           ("Allies in the Decree of Steadfastness also regenerate", "Los aliados en el Decreto de Firmeza también se regeneran")),
        base("imperial_lineage", "passive", 11, "decree_of_steadfastness", 1, 0),
        base("siege_decree", "active", 11, "decree_of_steadfastness", 1, 1),
        up("unbreaking_walls", 16, "siege_decree", 1, 2, ["siege_decree"], {"duration_s_add": 1, "radius_add": 0.5}, ("Unbreaking Walls", "Muros Inquebrantables"),
           ("Siege Decree lasts 1 s longer and covers 0.5 blocks more per rank", "Decreto de Asedio dura 1 s más y cubre 0.5 bloques más por rango")),
        base("voice_of_the_throne", "passive", 21, "imperial_lineage", 1, 0),
        base("bronze_cannon", "active", 21, "siege_decree", 1, 1),
        up("heavy_shot", 26, "bronze_cannon", 1, 0, ["bronze_cannon"], {"damage_bonus": 0.12, "shots_add": 0.5}, ("Heavy Shot", "Disparo Pesado"),
           ("Bronze Cannon shoots 12% harder and more often (2 more shots at rank 4)", "Cañón de Bronce dispara un 12% más fuerte y más veces (2 más en rango 4)")),
        up("grapeshot", 26, "bronze_cannon", 1, 2, ["bronze_cannon"], {"pellets": 1}, ("Grapeshot", "Metralla"),
           ("Bronze Cannon fires a spray of shot (1 more pellet per rank)", "Cañón de Bronce dispara metralla (1 perdigón más por rango)")),
        base("crown_of_the_five_lands", "ultimate", 30, "bronze_cannon", 1, 1),

        base("janissary_guard", "active", 1, None, 2, 1),
        up("brass_armor", 6, "janissary_guard", 2, 0, ["janissary_guard"], {"health_add": 4}, ("Brass Armor", "Armadura de Latón"),
           ("Janissaries have 4 more health per rank", "Los jenízaros tienen 4 de vida más por rango")),
        up("scimitar_drill", 6, "janissary_guard", 2, 2, ["janissary_guard"], {"guard_damage_add": 1}, ("Scimitar Drill", "Instrucción de Cimitarra"),
           ("Janissaries hit 1 harder per rank", "Los jenízaros pegan 1 más por rango")),
        base("royal_treasury", "active", 11, "janissary_guard", 2, 1),
        up("veteran_guard", 16, "brass_armor", 2, 0, ["janissary_guard"], {"duration_s_add": 5}, ("Veteran Guard", "Guardia Veterana"),
           ("Janissaries stay 5 s longer per rank", "Los jenízaros se quedan 5 s más por rango")),
        up("golden_rain", 16, "royal_treasury", 2, 2, ["royal_treasury"], {"coins_add": 1, "heal_bonus": 0.1}, ("Golden Rain", "Lluvia de Oro"),
           ("Royal Treasury throws 1 more coin, and each heals 10% more, per rank", "Tesoro Real lanza 1 moneda más y cada una cura un 10% más, por rango")),
        up("standing_army", 21, "veteran_guard", 2, 0, ["janissary_guard"], {"soldiers_add": 0.3}, ("Standing Army", "Ejército Permanente"),
           ("More Janissaries come (1 more at rank 4)", "Vienen más jenízaros (1 más en rango 4)")),
        up("war_chest", 21, "golden_rain", 2, 2, ["royal_treasury"], {"strength_s": 2}, ("War Chest", "Cofre de Guerra"),
           ("Royal coins also give Strength to whoever picks them up (2 s per rank)", "Las monedas reales también dan Fuerza a quien las recoja (2 s por rango)")),
        up("aetherium_guard", 26, "standing_army", 2, 0, ["janissary_guard"], {"resistance": 1}, ("Aetherium Guard", "Guardia de Aeterio"),
           ("Janissaries are tempered in aetherium: they take less damage", "Los jenízaros están templados en aeterio: reciben menos daño")),
        up("royal_mint", 26, "war_chest", 2, 1, ["royal_treasury"], {"cooldown_cut": 0.08, "cost_cut": 0.06}, ("Royal Mint", "Ceca Real"),
           ("Royal Treasury: 8% less cooldown and 6% less cost per rank", "Tesoro Real: 8% menos de enfriamiento y 6% menos de costo por rango")),
    ],
}
