"""The story content of Sprint 6 that is data: the Bearers' own quests for Acts I and II, the fate side quests of
Nordrath, what each Bearer says as an NPC and as a companion. scripts/make_story.py writes the quest and dialogue
JSON and the English and Spanish lines from here.

A Bearer quest is the player's own hero's: only a Knight gets Cassian's quests, and so on.
"""

CLASSES = ["knight", "necromancer", "sorceress", "thief", "king"]
HERO = {"knight": "cassian", "necromancer": "ankhareth", "sorceress": "shirin", "thief": "rurik", "king": "azhar"}

# id, class, act, giver, step 1 (reach target or None), spawn entity, count, reward relic, xp, title, lines
# lines: offer (2), accept answer, reminder, done (2) — each (en, es)
BEARER_QUESTS = [
    dict(id="cassian_act1", cls="knight", act=1, giver="citizen_veteran", reach=None, spawn="sofe:void_wretch", count=6, relic="knight_shield_charm", xp=400,
         title=("The Broken Banner", "El Estandarte Roto"),
         offer=[("You carry a banner nobody in Sulthari recognises, Knight. I fought beside men who carried it, long ago.",
                 "Llevas un estandarte que nadie en Sulthari reconoce, Caballero. Luché junto a hombres que lo llevaban, hace mucho."),
                ("The Void is gnawing at the lower district. Show me the Order of the Scale still stands, and I will tell you what I saw the night it fell.",
                 "El Vacío roe el distrito bajo. Muéstrame que la Orden de la Balanza sigue en pie y te contaré lo que vi la noche que cayó.")],
         accept=("Stand behind me, then.", "Entonces ponte detrás de mí."),
         reminder=("The Void is still in the lower district. The Scale does not hide.", "El Vacío sigue en el distrito bajo. La Balanza no se esconde."),
         done=[("You fought like them. Like the ones who did not betray you.", "Peleaste como ellos. Como los que no te traicionaron."),
               ("Your brothers did not fall to the Void. Gold opened the gates of the courts, gold from Aureum. Take this charm; it was your captain's.",
                "Tus hermanos no cayeron ante el Vacío. El oro abrió las puertas de los tribunales, oro de Aureum. Toma este talismán; era de tu capitán.")]),
    dict(id="cassian_act2", cls="knight", act=2, giver="nordrath_shieldmaiden", reach=("arena", 1200, -3000), spawn="sofe:void_stalker", count=6,
         relic="sunder_of_the_order", xp=1500, title=("The Oath Kept", "El Juramento Cumplido"),
         offer=[("Southerner. Vorath's voice speaks of you in the arena. He says your wrath is the sweetest he has smelled.",
                 "Sureño. La voz de Vorath habla de ti en la arena. Dice que tu ira es la más dulce que ha olido."),
                ("Go there and fight, but fight to protect. If you fight to destroy, he wins without lifting a hand.",
                 "Ve y pelea, pero pelea para proteger. Si peleas para destruir, él gana sin mover una mano.")],
         accept=("I fight for whoever stands behind me.", "Peleo por quien esté detrás de mí."),
         reminder=("The arena waits, east of the hold. Remember why you lift the shield.", "La arena espera, al este del bastión. Recuerda por qué levantas el escudo."),
         done=[("The warriors say you held the line and did not chase the ones who fled.", "Los guerreros dicen que sostuviste la línea y no perseguiste a los que huían."),
               ("That is the Scale I have heard of. Take this blade; my clan forged it for a knight who never came.",
                "Esa es la Balanza de la que oí hablar. Toma esta hoja; mi clan la forjó para un caballero que nunca llegó.")]),
    dict(id="ankhareth_act1", cls="necromancer", act=1, giver="citizen_widow", reach=None, spawn="sofe:void_wretch", count=6, relic="necro_scarab_charm", xp=400,
         title=("The Morgue's Papyri", "Los Papiros de la Morgue"),
         offer=[("You work in the morgue, embalmer. My husband lies there. Since the Eclipse he will not stay still.",
                 "Trabajas en la morgue, embalsamador. Mi esposo yace allí. Desde el Eclipse no se queda quieto."),
                ("The Void creatures are drawn to him. Drive them off, and give him the rest your people promised.",
                 "Las criaturas del Vacío se acercan a él. Ahuyéntalas y dale el descanso que tu pueblo prometía.")],
         accept=("The House of Thresholds keeps its word.", "La Casa de los Umbrales cumple su palabra."),
         reminder=("They still come for him at night. Please.", "Todavía vienen por él de noche. Por favor."),
         done=[("He is still. For the first time since the Eclipse, he is still.", "Está quieto. Por primera vez desde el Eclipse, está quieto."),
               ("He kept this scarab for you. He said the embalmer would need it more than the dead.",
                "Guardó este escarabajo para ti. Dijo que el embalsamador lo necesitaría más que los muertos.")]),
    dict(id="ankhareth_act2", cls="necromancer", act=2, giver="nordrath_elder", reach=("caverns", -600, -2400), spawn="sofe:void_stalker", count=6,
         relic="wand_of_the_ferryman", xp=1500, title=("Souls in the Snow", "Almas en la Nieve"),
         offer=[("Our dead do not go to the halls of their fathers anymore, priest of Khemet. They wander the caverns to the west.",
                 "Nuestros muertos ya no van a los salones de sus padres, sacerdote de Khemet. Vagan por las cavernas del oeste."),
                ("Something holds them there. You know the roads of the dead. Open the way.",
                 "Algo los retiene allí. Tú conoces los caminos de los muertos. Abre el paso.")],
         accept=("Every soul deserves its crossing.", "Toda alma merece su travesía."),
         reminder=("The caverns are west of the hold. Our dead are waiting.", "Las cavernas están al oeste del bastión. Nuestros muertos esperan."),
         done=[("The fires in the hall burned blue last night. The old ones say that is how the dead say farewell.",
                "Los fuegos del salón ardieron azules anoche. Los viejos dicen que así se despiden los muertos."),
               ("This wand was found in the caverns, older than our clans. It belongs to someone who guides the dead.",
                "Esta varita estaba en las cavernas, más vieja que nuestros clanes. Le pertenece a quien guía a los muertos.")]),
    dict(id="shirin_act1", cls="sorceress", act=1, giver="citizen_astronomer", reach=None, spawn="sofe:void_wretch", count=6, relic="sorc_ember_charm", xp=400,
         title=("Letters from Laleh", "Cartas de Laleh"),
         offer=[("Shirin! Letters keep arriving at the Observatory in your sister's hand, but they are dated after Parsivan fell.",
                 "¡Shirin! Siguen llegando cartas al Observatorio con la letra de tu hermana, pero tienen fecha posterior a la caída de Parsivan."),
                ("The Void gathers wherever the letters land. Clear them, and read what she wrote.",
                 "El Vacío se reúne donde caen las cartas. Despéjalo y lee lo que escribió.")],
         accept=("If she is writing, she is still there.", "Si está escribiendo, todavía está allí."),
         reminder=("The creatures still circle the letters. Be careful.", "Las criaturas todavía rodean las cartas. Ten cuidado."),
         done=[("The last letter says only: 'Stay with me in the garden, little star.'", "La última carta solo dice: 'Quédate conmigo en el jardín, pequeña estrella.'"),
               ("It was wrapped around this charm. It is warm, like an ember that never went out.",
                "Estaba envuelta alrededor de este talismán. Está tibio, como una brasa que nunca se apagó.")]),
    dict(id="shirin_act2", cls="sorceress", act=2, giver="nordrath_widow", reach=("forge", -1200, -3000), spawn="sofe:void_stalker", count=6,
         relic="laleh_lantern", xp=1500, title=("The Lantern in the Forge", "La Linterna de la Forja"),
         offer=[("A woman of the south came through the snow before the war, lady. She left a lantern at the forge and said a sister would come for it.",
                 "Una mujer del sur cruzó la nieve antes de la guerra, señora. Dejó una linterna en la forja y dijo que una hermana vendría por ella."),
                ("Kaleth's creatures guard the forge now.", "Ahora las criaturas de Kaleth vigilan la forja.")],
         accept=("Laleh. It was Laleh.", "Laleh. Era Laleh."),
         reminder=("The forge is west, past the frozen river.", "La forja está al oeste, pasando el río helado."),
         done=[("You found it. It still burns, after all this time.", "La encontraste. Todavía arde, después de tanto tiempo."),
               ("She said whoever carried it would never lose her way in the dark.", "Dijo que quien la llevara nunca se perdería en la oscuridad.")]),
    dict(id="rurik_act1", cls="thief", act=1, giver="bazaar_lampwright", reach=None, spawn="sofe:void_wretch", count=6, relic="thief_coin_charm", xp=400,
         title=("The Vault Job", "El Golpe a la Bóveda"),
         offer=[("Ash! The buyer for that shard is still waiting. The one stuck in your hand, yes.",
                 "¡Ceniza! El comprador de ese fragmento sigue esperando. El que tienes pegado a la mano, sí."),
                ("He won't pay for a hand. But the Void things in the bazaar scare my customers. Clear them and I'll pay you like old times.",
                 "No va a pagar por una mano. Pero las cosas del Vacío del bazar asustan a mis clientes. Despéjalas y te pago como en los viejos tiempos.")],
         accept=("Like old times. Double.", "Como en los viejos tiempos. El doble."),
         reminder=("They're still scaring off my customers, Ash.", "Siguen espantando a mis clientes, Ceniza."),
         done=[("Here's your pay. And something else: a man asked about you. A northerner, with a burned clan mark.",
                "Aquí está tu paga. Y algo más: un hombre preguntó por ti. Un norteño, con una marca de clan quemada."),
               ("He said the fire that took your village was no accident. He said a name: Fenrath.",
                "Dijo que el fuego que se llevó tu aldea no fue un accidente. Dijo un nombre: Fenrath.")]),
    dict(id="rurik_act2", cls="thief", act=2, giver="nordrath_raider", reach=("caverns", -600, -2400), spawn="sofe:void_stalker", count=6,
         relic="ash_and_ember", xp=1500, title=("Ashes of Grimsson", "Cenizas de Grimsson"),
         offer=[("Grimsson. I thought your clan burned to the last child.", "Grimsson. Creía que tu clan ardió hasta el último niño."),
                ("The raiders who did it hid their spoils in the western caverns. Some of it was yours.",
                 "Los saqueadores que lo hicieron escondieron el botín en las cavernas del oeste. Parte era tuyo.")],
         accept=("Then I'm stealing it back.", "Entonces lo voy a robar de vuelta."),
         reminder=("West caverns. Take back what is yours.", "Cavernas del oeste. Recupera lo que es tuyo.")),
    dict(id="azhar_act1", cls="king", act=1, giver="citizen_guard", reach=None, spawn="sofe:void_wretch", count=6, relic="king_coin_charm", xp=400,
         title=("The Throne's Debt", "La Deuda del Trono"),
         offer=[("Your Majesty! The people say the Sultan hides in the palace while the Void walks the streets.",
                 "¡Majestad! El pueblo dice que el Sultán se esconde en el palacio mientras el Vacío recorre las calles."),
                ("If they saw you fight beside the guard, they would believe again.", "Si te vieran pelear junto a la guardia, volverían a creer.")],
         accept=("Then let them see.", "Entonces que vean."),
         reminder=("The people are watching, Majesty.", "El pueblo está mirando, Majestad."),
         done=[("They cheered, Majesty. Even the old ones who cursed your grandfather.", "Te aclamaron, Majestad. Hasta los viejos que maldecían a tu abuelo."),
               ("The mint struck this coin for the day of your crowning. It was never given out. It is yours.",
                "La ceca acuñó esta moneda para el día de tu coronación. Nunca se repartió. Es tuya.")]),
    dict(id="azhar_act2", cls="king", act=2, giver="nordrath_hunter", reach=("forge", -1200, -3000), spawn="sofe:void_stalker", count=6,
         relic="scepter_of_the_first_sultan", xp=1500, title=("Envoy to the Clans", "Enviado a los Clanes"),
         offer=[("A sultan in the snow. The clans won't kneel to you, southerner.", "Un sultán en la nieve. Los clanes no se arrodillarán ante ti, sureño."),
                ("But they respect deeds. Free the forge from Kaleth's beasts, and they will listen to what Sulthari wants.",
                 "Pero respetan los hechos. Libera la forja de las bestias de Kaleth y escucharán lo que Sulthari quiere.")],
         accept=("Sulthari wants allies, not subjects.", "Sulthari quiere aliados, no súbditos."),
         reminder=("The forge, west. Deeds, not words.", "La forja, al oeste. Hechos, no palabras."),
         done=[("The clans saw. They say a sultan who bleeds for others is a sultan they could follow.",
                "Los clanes lo vieron. Dicen que un sultán que sangra por otros es un sultán al que podrían seguir."),
               ("This scepter came north with the first sultan's envoy, three hundred years ago. It goes back with you.",
                "Este cetro llegó al norte con el enviado del primer sultán, hace trescientos años. Regresa contigo.")]),
]
# Rurik's second quest ends with a choice of his own in its done lines
BEARER_QUESTS[7]["done"] = [("There it is: your father's knife, and a ledger with one name written in ash. Fenrath.",
                             "Ahí está: el cuchillo de tu padre, y un libro con un solo nombre escrito en ceniza. Fenrath."),
                            ("Whatever you do with that name, Grimsson, do it awake.", "Hagas lo que hagas con ese nombre, Grimsson, hazlo despierto.")]

# The fate side quests of Nordrath
FATE_QUESTS = [
    dict(id="nordrath_endless_war", giver="nordrath_skald", reach=("arena", 1200, -3000), spawn="minecraft:zombie", count=8, xp=1200,
         title=("The Endless War", "La Guerra Sin Fin"),
         offer=[("Hear the saga no skald wants to sing: the warriors who fell in Vorath's arena do not stay dead. They rise and fight again, forever.",
                 "Escucha la saga que ningún escaldo quiere cantar: los guerreros que cayeron en la arena de Vorath no se quedan muertos. Se alzan y pelean de nuevo, para siempre."),
                ("Go to the arena. Break the ones who rise. Then come back, and decide how the saga ends.",
                 "Ve a la arena. Quiebra a los que se alzan. Luego vuelve y decide cómo termina la saga.")],
         accept=("I'll go.", "Iré."),
         reminder=("The arena, east of the hold. The dead are still fighting.", "La arena, al este del bastión. Los muertos siguen peleando."),
         choice=[("You broke them, and they rose again. Only the ones who set the war can end it. You carry a shard of what set it.",
                  "Los quebraste y se alzaron de nuevo. Solo quien desató la guerra puede terminarla. Tú llevas un fragmento de lo que la desató."),
                 ("Will you free them, and let the clans mourn and make peace? Or let them fight forever, so the clans stay fierce for the wars to come?",
                  "¿Los liberarás, para que los clanes los lloren y hagan la paz? ¿O dejarás que peleen para siempre, para que los clanes sigan feroces para las guerras que vendrán?")],
         answers=[("peace", ("Free them. Let the clans mourn.", "Libéralos. Que los clanes los lloren."), ("Then the saga ends in silence. A good silence.", "Entonces la saga termina en silencio. Un buen silencio.")),
                  ("war", ("Let them fight. The north will need warriors.", "Que peleen. El norte necesitará guerreros."), ("Then the saga never ends. The clans will remember your choice.", "Entonces la saga nunca termina. Los clanes recordarán tu elección."))]),
    dict(id="nordrath_cold_forge", giver="nordrath_runesmith", reach=("forge", -1200, -3000), spawn="sofe:void_stalker", count=6, xp=900, reward_item=("sofe:glacial_iron_ingot", 8),
         title=("The Cold Forge", "La Forja Fría"),
         offer=[("The great forge of the north went cold when Kaleth took it. Without it, no glacial iron for the clans.",
                 "La gran forja del norte se enfrió cuando Kaleth la tomó. Sin ella, no hay hierro glacial para los clanes."),
                ("His beasts still guard the anvils. Clear them, and I'll light it again.", "Sus bestias todavía guardan los yunques. Despéjalas y la encenderé de nuevo.")],
         accept=("Light the fires, smith.", "Enciende los fuegos, herrero."),
         reminder=("The forge, west of the hold.", "La forja, al oeste del bastión."),
         done=[("The forge burns again! The first ingots are yours.", "¡La forja arde otra vez! Los primeros lingotes son tuyos."),
               ("Whatever the clans decide about the war, they'll fight it with good steel now.", "Decidan lo que decidan los clanes sobre la guerra, ahora la pelearán con buen acero.")]),
]

# How Nordrath remembers the fate: the skald's line once it is set
FATE_REACTIONS = {
    "peace": ("The warriors of the arena rest. The clans sang for them three nights. I sang the loudest.",
              "Los guerreros de la arena descansan. Los clanes les cantaron tres noches. Yo canté más fuerte."),
    "war": ("Hear them? Steel on steel, every night, from the arena. The young ones go to watch, and come back hungry for war.",
            "¿Los oyes? Acero contra acero, cada noche, desde la arena. Los jóvenes van a mirar y vuelven con hambre de guerra."),
}

# The Bearers as NPCs: what they say in each act, and their answer when hired
BEARER_LINES = {
    "knight": {1: ("The shard chose me because I stepped in front of a child. I would do it again.", "El fragmento me eligió porque me puse delante de un niño. Lo volvería a hacer."),
               2: ("Vorath whispers that I could end all of this with enough rage. He is right. That is what frightens me.",
                   "Vorath me susurra que podría terminar con todo esto con suficiente ira. Tiene razón. Eso es lo que me asusta.")},
    "necromancer": {1: ("The dead in this city are restless. I hear them at night, asking which way to go.", "Los muertos de esta ciudad están inquietos. Los oigo de noche, preguntando por dónde ir."),
                    2: ("Sometimes I think it would be easy to lie down beside them and sleep. Morthis would like that.",
                        "A veces pienso que sería fácil acostarme junto a ellos y dormir. A Morthis le gustaría.")},
    "sorceress": {1: ("Laleh taught me to read the stars. Now they read me back.", "Laleh me enseñó a leer las estrellas. Ahora ellas me leen a mí."),
                  2: ("In my dreams the gardens are warm and she is laughing. I wake up colder every time.",
                      "En mis sueños los jardines son cálidos y ella se ríe. Me despierto más fría cada vez.")},
    "thief": {1: ("Somebody's paying good money for this shard. Shame it's stuck to my hand.", "Alguien está pagando buen dinero por este fragmento. Lástima que esté pegado a mi mano."),
              2: ("The north smells like my village did. Before the fire.", "El norte huele como olía mi aldea. Antes del fuego.")},
    "king": {1: ("My ancestor opened this door. The least I can do is help close it.", "Mi antepasado abrió esta puerta. Lo mínimo que puedo hacer es ayudar a cerrarla."),
             2: ("The clans respect strength, not crowns. I am learning which one I have.", "Los clanes respetan la fuerza, no las coronas. Estoy aprendiendo cuál de las dos tengo.")},
}
HIRE = {"offer": ("Will you travel with me?", "¿Viajarás conmigo?"),
        "yes": ("Travel with me.", "Viaja conmigo."), "no": ("Not now.", "Ahora no.")}

# The companion's own words: hired, sent away, beaten, a boss falls, and one line per region it enters
COMPANION = {
    "knight": dict(name=("Cassian", "Cassian"), hired=("My shield is yours. Lead.", "Mi escudo es tuyo. Guía."),
                   dismissed=("I'll be in Sulthari, by the palace. Call if you need a wall.", "Estaré en Sulthari, junto al palacio. Llama si necesitas un muro."),
                   down=("I... must fall back. To Sulthari.", "Debo... replegarme. A Sulthari."), boss=("One less voice in the dark.", "Una voz menos en la oscuridad."),
                   regions={"sulthari": ("Home, for now.", "Hogar, por ahora."), "nordrath": ("I can feel Vorath's rage in the air. Keep me from it.", "Siento la ira de Vorath en el aire. No me dejes caer en ella."),
                            "parsivan": ("Flowers that smell of sleep. Stay awake.", "Flores que huelen a sueño. Mantente despierto."),
                            "khemet": ("The dead here are too quiet.", "Los muertos aquí están demasiado callados."),
                            "aureum": ("Aureum. The courts where my order died. Let me pass judgment.", "Aureum. Los tribunales donde murió mi orden. Déjame juzgar.")}),
    "necromancer": dict(name=("Ankhareth", "Ankhareth"), hired=("The dead will walk beside us. Do not be afraid of them.", "Los muertos caminarán con nosotros. No les temas."),
                        dismissed=("I return to the morgue. Someone has to listen to them.", "Vuelvo a la morgue. Alguien tiene que escucharlos."),
                        down=("My thread is cut... for now.", "Mi hilo está cortado... por ahora."), boss=("Its soul goes where it must.", "Su alma va adonde debe ir."),
                        regions={"sulthari": ("Sulthari's dead are restless tonight.", "Los muertos de Sulthari están inquietos esta noche."),
                                 "nordrath": ("The northern dead want to fight even after death.", "Los muertos del norte quieren pelear incluso después de morir."),
                                 "parsivan": ("The dreamers here are neither dead nor alive.", "Los soñadores aquí no están ni vivos ni muertos."),
                                 "khemet": ("Khemet. My home. Morthis will try to make me sleep. Do not let me.", "Khemet. Mi hogar. Morthis intentará hacerme dormir. No me dejes."),
                                 "aureum": ("So much gold, and the dead still unpaid.", "Tanto oro, y los muertos aún sin pagar.")}),
    "sorceress": dict(name=("Shirin", "Shirin"), hired=("The stars say we'll go far together.", "Las estrellas dicen que llegaremos lejos juntos."),
                      dismissed=("I'll be at the Observatory, reading the sky for you.", "Estaré en el Observatorio, leyendo el cielo para ti."),
                      down=("The stars... went dark. Sulthari...", "Las estrellas... se apagaron. Sulthari..."), boss=("Write that one down in the stars.", "Escribe ese en las estrellas."),
                      regions={"sulthari": ("The Observatory is watching us.", "El Observatorio nos está mirando."),
                               "nordrath": ("Too cold for poetry. Not too cold for fire.", "Demasiado frío para la poesía. No para el fuego."),
                               "parsivan": ("Parsivan... I can hear her. Laleh is calling. Hold my hand.", "Parsivan... la oigo. Laleh me está llamando. Toma mi mano."),
                               "khemet": ("The stars here are older than the sand.", "Las estrellas aquí son más viejas que la arena."),
                               "aureum": ("Marble and lies. Watch your back.", "Mármol y mentiras. Cuida tu espalda.")}),
    "thief": dict(name=("Rurik", "Rurik"), hired=("Sure. What's my cut?", "Claro. ¿Cuál es mi parte?"), dismissed=("I'll be in the Low Bazaar. Don't let anyone sell you fake relics.", "Estaré en el Bazar Bajo. No dejes que nadie te venda reliquias falsas."),
                  down=("Ugh. I'm out. See you at the bazaar.", "Uf. Me retiro. Nos vemos en el bazar."), boss=("Anything worth taking on it?", "¿Lleva algo que valga la pena?"),
                  regions={"sulthari": ("Sulthari. Smell of spice and debts.", "Sulthari. Huele a especias y deudas."),
                           "nordrath": ("Home. Or what's left of it.", "Hogar. O lo que queda de él."),
                           "parsivan": ("Pretty place. Too pretty. Check your pockets.", "Lugar bonito. Demasiado bonito. Revisa tus bolsillos."),
                           "khemet": ("Tombs full of gold, and nobody guarding them? That's a trap.", "Tumbas llenas de oro y nadie cuidándolas? Eso es una trampa."),
                           "aureum": ("Avarok's vaults are here. Don't let me near them.", "Las bóvedas de Avarok están aquí. No me dejes acercarme a ellas.")}),
    "king": dict(name=("Azhar", "Azhar"), hired=("Sulthari's crown walks with you.", "La corona de Sulthari camina contigo."),
                 dismissed=("I return to the palace. The Council will want a report.", "Vuelvo al palacio. El Consejo querrá un informe."),
                 down=("Even sultans must retreat. To the palace.", "Hasta los sultanes deben retirarse. Al palacio."), boss=("Let them write it in the chronicles.", "Que lo escriban en las crónicas."),
                 regions={"sulthari": ("My city. My people. My debt.", "Mi ciudad. Mi pueblo. Mi deuda."),
                          "nordrath": ("The clans watch me like a wolf watches a lamb. Let them.", "Los clanes me miran como un lobo mira a un cordero. Que miren."),
                          "parsivan": ("Parsivan's court once sent us roses every spring.", "La corte de Parsivan nos enviaba rosas cada primavera."),
                          "khemet": ("My grandfather's diary spoke of Khemet. Little of it was kind.", "El diario de mi abuelo hablaba de Khemet. Poco era amable."),
                          "aureum": ("Aureum. Where emperors forget they are men. Remind me, if I do.", "Aureum. Donde los emperadores olvidan que son hombres. Recuérdamelo, si me pasa.")}),
}
ORDERS = {"follow": ("Follow me.", "Sígueme."), "stay": ("Wait here.", "Espera aquí."), "dismiss": ("Go back to Sulthari.", "Vuelve a Sulthari."),
          "greet": ("What do you need?", "¿Qué necesitas?")}
